# Generated by Django 5.2.15 on 2026-06-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_timestamps_notnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('new_order', 'New order'), ('ready', 'Ready'), ('awaiting_payment', 'Awaiting payment'), ('needs_service', 'Needs service'), ('late', 'Late'), ('closed', 'Closed')], default='free', max_length=32),
        ),
    ]
