from decimal import Decimal

from django.db import migrations

# (name, category, station, price, description, composition, is_available)
# Sourced from the printed Sissi menu file: the 104 core items are active,
# the 185 expanded variants are loaded but inactive (stop-listed).
ITEMS = [
    ('Analcolico Sissi', 'Analcolici', 'bar', '8.00', '', '', True),
    ('Crodino/San Bitter', 'Analcolici', 'bar', '6.00', '', '', True),
    ('Lurisia Assenzio o Genziana', 'Analcolici', 'bar', '6.00', '', '', True),
    ('Succo di pomodoro condito', 'Analcolici', 'bar', '6.00', '', '', True),
    ('Americano/Negroni', 'Aperitivi', 'bar', '10.00', '', '', True),
    ('Aperol Spritz', 'Aperitivi', 'bar', '8.00', '', '', True),
    ('Campari Shakerato', 'Aperitivi', 'bar', '7.00', '', '', True),
    ('Campari Soda', 'Aperitivi', 'bar', '6.00', '', '', True),
    ('Daiquiri/Mimosa', 'Aperitivi', 'bar', '10.00', '', '', True),
    ('Limoncello Spritz', 'Aperitivi', 'bar', '10.00', '', '', True),
    ('Negroni Sbagliato/Negrosky', 'Aperitivi', 'bar', '10.00', '', '', True),
    ('Acqua 0,5 l', 'Bibite', 'bar', '2.50', '', '', True),
    ('Coca-Cola/Sprite', 'Bibite', 'bar', '4.50', '', '', True),
    ('Lemonsoda/Aranciata', 'Bibite', 'bar', '4.50', '', '', True),
    ('Limonata/Chinotto', 'Bibite', 'bar', '4.50', '', '', True),
    ("Spremuta d'arancia", 'Bibite', 'bar', '6.00', '', '', True),
    ('Succo di frutta', 'Bibite', 'bar', '4.00', '', '', True),
    ('Tonica/Cedrata', 'Bibite', 'bar', '4.50', '', '', True),
    ('Tè freddo', 'Bibite', 'bar', '4.00', '', '', True),
    ('Birra in bottiglia 0,33 l', 'Birra', 'bar', '5.00', '', '', True),
    ('Kronenbourg 1664 alla spina 0,25 l', 'Birra', 'bar', '4.00', '', '', True),
    ('Kronenbourg 1664 alla spina 0,5 l', 'Birra', 'bar', '7.00', '', '', True),
    ('Peroni Gran Riserva Doppio Malto 0,5 l', 'Birra', 'bar', '7.50', '', '', True),
    ('Americano', 'Caffetteria', 'bar', '2.00', '', '', True),
    ('Bombardino', 'Caffetteria', 'bar', '5.00', '', '', True),
    ('Caffè con panna', 'Caffetteria', 'bar', '2.50', '', '', True),
    ('Cappuccino', 'Caffetteria', 'bar', '3.00', '', '', True),
    ('Cappuccino con miele e cannella', 'Caffetteria', 'bar', '4.00', '', '', True),
    ('Cioccolata calda con panna', 'Caffetteria', 'bar', '6.00', '', '', True),
    ('Corretto', 'Caffetteria', 'bar', '3.00', '', '', True),
    ('Decaffeinato', 'Caffetteria', 'bar', '2.00', '', '', True),
    ('Espresso', 'Caffetteria', 'bar', '1.50', '', '', True),
    ('Flat White', 'Caffetteria', 'bar', '5.00', '', '', True),
    ('Latte bianco', 'Caffetteria', 'bar', '2.00', '', '', True),
    ('Latte macchiato', 'Caffetteria', 'bar', '3.50', '', '', True),
    ('Orzo/Ginseng grande', 'Caffetteria', 'bar', '3.00', '', '', True),
    ('Orzo/Ginseng piccolo', 'Caffetteria', 'bar', '2.00', '', '', True),
    ('Punch', 'Caffetteria', 'bar', '5.00', '', '', True),
    ('Tè/Tisana', 'Caffetteria', 'bar', '3.50', '', '', True),
    ('Vin brulè', 'Caffetteria', 'bar', '6.00', '', '', True),
    ('Bloody Mary', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Caipiroska/Caipirinha', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Cosmopolitan', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Cuba Libre', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Gin Tonic Base Bombay', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Long Island Iced Tea', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Margarita', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Moscow Mule', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Premium Cocktails', 'Cocktails', 'bar', '14.00', '', '', True),
    ('Sex on the Beach', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Sissi Signature Cocktail', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Tequila Sunrise', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Vodka Tonic', 'Cocktails', 'bar', '12.00', '', '', True),
    ('Baby Toast', 'Colazione', 'kitchen', '6.00', '', '', True),
    ('Biscotto Occhio di Bue', 'Colazione', 'kitchen', '3.70', '', 'Marmellata o Nutella', True),
    ('Croissant o krapfen', 'Colazione', 'kitchen', '2.50', '', 'Crema, marmellata, Nutella o pistacchio', True),
    ('Croissant vegano', 'Colazione', 'kitchen', '3.00', '', '', True),
    ('Crêpe con Nutella o miele', 'Colazione', 'kitchen', '7.00', '', '', True),
    ('Crêpe cotto e fontina', 'Colazione', 'kitchen', '8.00', '', '', True),
    ('French Toast con miele e noci', 'Colazione', 'kitchen', '13.00', '', '', True),
    ('Omelette cotto e fontina', 'Colazione', 'kitchen', '13.00', '', '', True),
    ('Pan carré tostato', 'Colazione', 'kitchen', '13.00', '', '', True),
    ('Toast classico cotto e formaggio', 'Colazione', 'kitchen', '7.00', '', '', True),
    ("Uovo all'occhio di bue", 'Colazione', 'kitchen', '13.00', '', 'Bacon e pan carré tostato', True),
    ('Cotoletta con patatine fritte', 'Cucina di Sissi', 'kitchen', '16.00', '', '', True),
    ('Patatine fritte', 'Cucina di Sissi', 'kitchen', '5.50', '', '', True),
    ('Tortel di patate con la Caprese', 'Cucina di Sissi', 'kitchen', '14.00', '', '', True),
    ('Tortel di patate con lardo e miele', 'Cucina di Sissi', 'kitchen', '16.00', '', '', True),
    ('Tortel di patate con salsiccia', 'Cucina di Sissi', 'kitchen', '18.00', '', 'Formaggio alla piastra e crauti', True),
    ('Tortel di patate con uova e bacon', 'Cucina di Sissi', 'kitchen', '16.00', '', '', True),
    ('Patatine fritte', 'Da stuzzicare', 'kitchen', '5.50', '', '', True),
    ('Sticks misti da stuzzicare', 'Da stuzzicare', 'kitchen', '25.00', '', 'Sticks di polenta, rosti di patate, speck, lardo, miele, formaggio e noci', True),
    ('Cheesecake Sissi', 'Dolci', 'kitchen', '7.00', '', '', True),
    ('Crostata del giorno', 'Dolci', 'kitchen', '5.00', '', '', True),
    ('Crostata vegana', 'Dolci', 'kitchen', '5.50', '', '', True),
    ('Crêpes con Nutella', 'Dolci', 'kitchen', '7.00', '', '', True),
    ('Sacher con la panna', 'Dolci', 'kitchen', '6.50', '', '', True),
    ('Strüdel di mele', 'Dolci', 'kitchen', '6.50', '', 'Salsa di vaniglia e panna', True),
    ('Torta di carote con gelato', 'Dolci', 'kitchen', '7.00', '', '', True),
    ('Torta di carote con la panna', 'Dolci', 'kitchen', '6.50', '', '', True),
    ('Amari', 'Grappe e liquori', 'bar', '6.00', '', '', True),
    ('Grappa Barricata / 18 lune', 'Grappe e liquori', 'bar', '6.00', '', '', True),
    ('Grappe e liquori', 'Grappe e liquori', 'bar', '5.00', '', '', True),
    ('Bocconcino Sissi', 'Panini', 'kitchen', '12.00', '', 'Würstel, ketchup e cipolla caramellata', True),
    ('Burgherita Sissi', 'Panini', 'kitchen', '14.00', 'Extra: uovo, bacon, cetriolini, cipolla fritta o caramellata + €1.50', 'Burger bun, hamburger di manzo, cheddar, pomodoro, insalata e salsa', True),
    ('Hamburger vegetariano', 'Panini', 'kitchen', '14.00', '', 'Burger bun, burger ai vegetali grigliati, scamorza, pomodoro, insalata, cipolla fritta e salsa', True),
    ('Hot Dog Alpino', 'Panini', 'kitchen', '12.00', '', 'Würstel, senape e crauti', True),
    ('Montantaro', 'Panini', 'kitchen', '12.00', '', 'Porchetta, insalata, salsa tartara e cipolla fritta', True),
    ('Rendena', 'Panini', 'kitchen', '8.50', '', 'Speck, formaggio Casolet e salsa tartara', True),
    ('Snowboard', 'Panini', 'kitchen', '13.00', '', 'Cotoletta, maionese, pomodorino, insalata e cipolla fritta', True),
    ('Tirolese', 'Panini', 'kitchen', '12.00', '', 'Würstel, maionese e cipolla fritta', True),
    ('Vegetariano', 'Panini', 'kitchen', '8.00', '', 'Mozzarella e pomodoro', True),
    ('Piadina cotto', 'Spuntino Salato', 'kitchen', '8.00', '', 'Formaggio, pomodoro e insalata', True),
    ('Piadina speck', 'Spuntino Salato', 'kitchen', '8.80', '', 'Brie, miele, noci e rucola', True),
    ('Sissi Club Sandwich', 'Spuntino Salato', 'kitchen', '8.00', '', 'Tacchino, pomodoro, maionese e insalata', True),
    ('Toast vegetariano', 'Spuntino Salato', 'kitchen', '7.00', '', 'Fontina, pomodoro e insalata', True),
    ('Gewürztraminer', 'Vino al calice e bottiglie', 'bar', '6.00', 'Calice. Bottiglia: €33.', '', True),
    ('Lagrein', 'Vino al calice e bottiglie', 'bar', '6.00', 'Calice. Bottiglia: €35.', '', True),
    ('Lugana', 'Vino al calice e bottiglie', 'bar', '6.00', 'Calice. Bottiglia: €33.', '', True),
    ('Marzemino', 'Vino al calice e bottiglie', 'bar', '6.00', 'Calice. Bottiglia: €35.', '', True),
    ('Pinot grigio', 'Vino al calice e bottiglie', 'bar', '6.00', 'Calice. Bottiglia: €33.', '', True),
    ('Prosecco Valdobbiadene', 'Vino al calice e bottiglie', 'bar', '6.00', 'Calice. Bottiglia: €33.', '', True),
    ('Teroldego', 'Vino al calice e bottiglie', 'bar', '6.00', 'Calice. Bottiglia: €35.', '', True),
    ('Trento DOC', 'Vino al calice e bottiglie', 'bar', '8.00', 'Calice. Bottiglia: €52.', '', True),
    ('Americano', 'Aperitivi', 'bar', '10.00', '', '', False),
    ('Analcolico Frutta', 'Aperitivi', 'bar', '8.00', '', '', False),
    ('Aperitivo Assenzio Lurisia', 'Aperitivi', 'bar', '6.00', '', '', False),
    ('Aperitivo Lurisia Genziana', 'Aperitivi', 'bar', '6.00', '', '', False),
    ('Aurora Boreale', 'Aperitivi', 'bar', '14.00', '', '', False),
    ("Baby It's Cold", 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Bloody Virgin', 'Aperitivi', 'bar', '6.00', '', '', False),
    ('Cinnamon Snow Mule', 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Cocktail 12€ Base', 'Aperitivi', 'bar', '12.00', '', '', False),
    ('Coconut Snowdrift', 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Forst', 'Aperitivi', 'bar', '5.00', '', '', False),
    ('Franz Joseph Spritz', 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Frosted Maracuja', 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Gin Tonic 12€ Base', 'Aperitivi', 'bar', '12.00', '', '', False),
    ('Gingerbread Martini', 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Hugo', 'Aperitivi', 'bar', '8.00', '', '', False),
    ('Lavender Spritz', 'Aperitivi', 'bar', '12.00', '', '', False),
    ('Marshmallow Martini', 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Martini', 'Aperitivi', 'bar', '6.00', '', '', False),
    ('Media Grimbergen', 'Aperitivi', 'bar', '8.00', '', '', False),
    ('Media Kronenbourg', 'Aperitivi', 'bar', '7.00', '', '', False),
    ('Merry Kiss Shot', 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Mr Sandman', 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Negroni', 'Aperitivi', 'bar', '10.00', '', '', False),
    ('Negrosky', 'Aperitivi', 'bar', '10.00', '', '', False),
    ('Piccola Kronenbourg', 'Aperitivi', 'bar', '4.00', '', '', False),
    ('Radler Media', 'Aperitivi', 'bar', '7.00', '', '', False),
    ('Radler Piccola', 'Aperitivi', 'bar', '4.00', '', '', False),
    ('Snowflake', 'Aperitivi', 'bar', '14.00', '', '', False),
    ('Spritz Estivo', 'Aperitivi', 'bar', '12.00', '', '', False),
    ('Spritz Misto', 'Aperitivi', 'bar', '8.00', '', '', False),
    ('ACE Succo', 'Bevande', 'bar', '4.00', '', '', False),
    ('Acqua 0,5 Asporto', 'Bevande', 'bar', '2.00', '', '', False),
    ('Acqua 0,5 Frizz Pejo', 'Bevande', 'bar', '2.50', '', '', False),
    ('Acqua 0,5 Nat. Pejo', 'Bevande', 'bar', '2.50', '', '', False),
    ('Acqua 1 L Pejo', 'Bevande', 'bar', '4.00', '', '', False),
    ('Acqua 1 Litro Asporto', 'Bevande', 'bar', '3.50', '', '', False),
    ('Acqua Menta Lampone', 'Bevande', 'bar', '3.00', '', '', False),
    ('Albicocca Succo', 'Bevande', 'bar', '4.00', '', '', False),
    ('Ananas Succo', 'Bevande', 'bar', '4.00', '', '', False),
    ('Aranciata', 'Bevande', 'bar', '4.50', '', '', False),
    ('Bicchiere H2O', 'Bevande', 'bar', '0.50', '', '', False),
    ('Bicchiere H2O Frizzante', 'Bevande', 'bar', '0.50', '', '', False),
    ('Cedrata', 'Bevande', 'bar', '4.50', '', '', False),
    ('Chinotto', 'Bevande', 'bar', '4.50', '', '', False),
    ('Coca Cola', 'Bevande', 'bar', '4.50', '', '', False),
    ('Coca Zero', 'Bevande', 'bar', '4.50', '', '', False),
    ('Crodino', 'Bevande', 'bar', '6.00', '', '', False),
    ('Energy Drink', 'Bevande', 'bar', '4.50', '', '', False),
    ('Lemonsoda', 'Bevande', 'bar', '4.50', '', '', False),
    ('Let It Snow', 'Bevande', 'bar', '11.50', '', '', False),
    ('Limonata', 'Bevande', 'bar', '4.50', '', '', False),
    ('Mela Succo', 'Bevande', 'bar', '4.00', '', '', False),
    ('Milkshake', 'Bevande', 'bar', '7.00', '', '', False),
    ('Mirtillo Succo', 'Bevande', 'bar', '4.00', '', '', False),
    ('Pera Succo', 'Bevande', 'bar', '4.00', '', '', False),
    ('Pesca Succo', 'Bevande', 'bar', '4.00', '', '', False),
    ('Red Bull', 'Bevande', 'bar', '6.00', '', '', False),
    ('Sanbitter', 'Bevande', 'bar', '6.00', '', '', False),
    ('Sissi Mocktail', 'Bevande', 'bar', '11.50', '', '', False),
    ('Sprite', 'Bevande', 'bar', '4.50', '', '', False),
    ('Succo Pomodoro', 'Bevande', 'bar', '4.00', '', '', False),
    ('Tè Limone', 'Bevande', 'bar', '4.00', '', '', False),
    ('Tè Pesca', 'Bevande', 'bar', '4.00', '', '', False),
    ('Caffè Shakerato', 'Caffetteria', 'bar', '5.00', '', '', False),
    ('Camomilla', 'Caffetteria', 'bar', '3.00', '', '', False),
    ('Cappuccino Deca', 'Caffetteria', 'bar', '3.50', '', '', False),
    ('Cappuccino Panna', 'Caffetteria', 'bar', '5.00', '', '', False),
    ('Cappuccino Soya', 'Caffetteria', 'bar', '3.50', '', '', False),
    ('Cappuccio Orzo', 'Caffetteria', 'bar', '3.50', '', '', False),
    ('Cioccolata Arancia Cannella', 'Caffetteria', 'bar', '7.00', '', '', False),
    ('Cioccolata Baby', 'Caffetteria', 'bar', '3.00', '', '', False),
    ('Cioccolata Bianca Menta', 'Caffetteria', 'bar', '6.50', '', '', False),
    ('Cioccolata Calda', 'Caffetteria', 'bar', '5.50', '', '', False),
    ('Cioccolata Calda Bianca', 'Caffetteria', 'bar', '5.50', '', '', False),
    ('Cioccolata Cocco Mou', 'Caffetteria', 'bar', '7.00', '', '', False),
    ('Cioccolata Peperoncino', 'Caffetteria', 'bar', '7.00', '', '', False),
    ('Deca Macchiato', 'Caffetteria', 'bar', '2.00', '', '', False),
    ('Deca Macchiato Freddo', 'Caffetteria', 'bar', '2.00', '', '', False),
    ('Doppio Caffè', 'Caffetteria', 'bar', '3.00', '', '', False),
    ('Ginseng Grande', 'Caffetteria', 'bar', '3.00', '', '', False),
    ('Ginseng Piccolo', 'Caffetteria', 'bar', '2.50', '', '', False),
    ('Latte Caldo', 'Caffetteria', 'bar', '2.00', '', '', False),
    ('Lungo Caffè', 'Caffetteria', 'bar', '1.50', '', '', False),
    ('Macchiato', 'Caffetteria', 'bar', '1.50', '', '', False),
    ('Macchiato Freddo', 'Caffetteria', 'bar', '1.50', '', '', False),
    ('Macchiatone', 'Caffetteria', 'bar', '2.00', '', '', False),
    ('Marocchino', 'Caffetteria', 'bar', '2.50', '', '', False),
    ('No Lattosio Cappuccio', 'Caffetteria', 'bar', '3.00', '', '', False),
    ('Orzo Grande', 'Caffetteria', 'bar', '3.00', '', '', False),
    ('Orzo Macchiato', 'Caffetteria', 'bar', '2.50', '', '', False),
    ('Orzo Piccolo', 'Caffetteria', 'bar', '2.50', '', '', False),
    ('Punch Mandarino', 'Caffetteria', 'bar', '5.00', '', '', False),
    ('Ristretto', 'Caffetteria', 'bar', '1.50', '', '', False),
    ('Schiumetta', 'Caffetteria', 'bar', '1.50', '', '', False),
    ('Schiumetta Piccola', 'Caffetteria', 'bar', '1.50', '', '', False),
    ('Fagottino Mela', 'Dolci', 'kitchen', '3.50', '', '', False),
    ('Fetta Crostata Asporto', 'Dolci', 'kitchen', '4.00', '', '', False),
    ('Fetta Sacher Asporto', 'Dolci', 'kitchen', '5.50', '', '', False),
    ('Fetta Strudel Asporto', 'Dolci', 'kitchen', '5.50', '', '', False),
    ('Gluten Free Snack', 'Dolci', 'kitchen', '3.00', '', '', False),
    ('Krapfen Crema', 'Dolci', 'kitchen', '2.50', '', '', False),
    ('Krapfen Marmellata', 'Dolci', 'kitchen', '2.50', '', '', False),
    ('Krapfen Nutella', 'Dolci', 'kitchen', '2.50', '', '', False),
    ('Krapfen Pistacchio', 'Dolci', 'kitchen', '3.00', '', '', False),
    ('Krapfen Vuoto', 'Dolci', 'kitchen', '2.50', '', '', False),
    ('Lintz', 'Dolci', 'kitchen', '6.50', '', '', False),
    ('Macarons', 'Dolci', 'kitchen', '2.00', '', '', False),
    ('Marshmallow Piccolo', 'Dolci', 'kitchen', '0.50', '', '', False),
    ('Mele Torta', 'Dolci', 'kitchen', '6.50', '', '', False),
    ('Meringa', 'Dolci', 'kitchen', '1.50', '', '', False),
    ('Mignon Pasticcini', 'Dolci', 'kitchen', '1.50', '', '', False),
    ('Mini Sacherina', 'Dolci', 'kitchen', '2.50', '', '', False),
    ('Muffin', 'Dolci', 'kitchen', '3.80', '', '', False),
    ('Occhio Bue Cioccolato', 'Dolci', 'kitchen', '3.70', '', '', False),
    ('Occhio di Bue Marmellata', 'Dolci', 'kitchen', '3.70', '', '', False),
    ('Sacher', 'Dolci', 'kitchen', '6.50', '', '', False),
    ('Senza Glutine Senza Lattosio', 'Dolci', 'kitchen', '12.00', '', '', False),
    ('Sissi Souvenir', 'Dolci', 'kitchen', '5.90', '', '', False),
    ('Strudel + Vaniglia Gelato', 'Dolci', 'kitchen', '7.50', '', '', False),
    ('Strudel Piccolo', 'Dolci', 'kitchen', '18.50', '', '', False),
    ('Torta di Carote', 'Dolci', 'kitchen', '6.00', '', '', False),
    ('Panino Speck', 'Food', 'kitchen', '8.50', '', '', False),
    ('Piadina Light', 'Food', 'kitchen', '8.50', '', '', False),
    ('Piadina Salame', 'Food', 'kitchen', '8.50', '', '', False),
    ('Piadina Vegetariana', 'Food', 'kitchen', '8.00', '', '', False),
    ('Tortel Lardo o Speck', 'Food', 'kitchen', '16.00', '', '', False),
    ('Tortel Uova', 'Food', 'kitchen', '16.00', '', '', False),
    ('2 Gusti Take Away', 'Gelati', 'kitchen', '3.50', '', '', False),
    ('Affogato Baileys', 'Gelati', 'kitchen', '10.00', '', '', False),
    ('Affogato al Caffè', 'Gelati', 'kitchen', '4.00', '', '', False),
    ('Cono Coppetta 1', 'Gelati', 'kitchen', '2.00', '', '', False),
    ('Cono Coppetta 2', 'Gelati', 'kitchen', '3.50', '', '', False),
    ('Cono Coppetta 3', 'Gelati', 'kitchen', '4.50', '', '', False),
    ('Coppa 1', 'Gelati', 'kitchen', '3.50', '', '', False),
    ('Coppa 2', 'Gelati', 'kitchen', '5.00', '', '', False),
    ('Coppa 3', 'Gelati', 'kitchen', '6.50', '', '', False),
    ('Frappè', 'Gelati', 'kitchen', '8.50', '', '', False),
    ('Gelato 1 Chilo', 'Gelati', 'kitchen', '24.00', '', '', False),
    ('Gelato 500 g', 'Gelati', 'kitchen', '12.00', '', '', False),
    ('Jingle Bell Rock', 'Gelati', 'kitchen', '11.50', '', '', False),
    ('Amaro Trentino', 'Liquori', 'bar', '6.00', '', '', False),
    ('Amaro del Capo', 'Liquori', 'bar', '6.00', '', '', False),
    ('Anima Nera', 'Liquori', 'bar', '5.00', '', '', False),
    ('Asperula', 'Liquori', 'bar', '5.00', '', '', False),
    ('Averna', 'Liquori', 'bar', '6.00', '', '', False),
    ('Baileys', 'Liquori', 'bar', '6.00', '', '', False),
    ('Barricata', 'Liquori', 'bar', '6.00', '', '', False),
    ('Braulio', 'Liquori', 'bar', '6.00', '', '', False),
    ('Cacao Nocciola', 'Liquori', 'bar', '6.00', '', '', False),
    ('Camomilla Grappa', 'Liquori', 'bar', '5.00', '', '', False),
    ('Caramello Salato', 'Liquori', 'bar', '6.00', '', '', False),
    ('Cirmolo', 'Liquori', 'bar', '5.00', '', '', False),
    ('Cointreau', 'Liquori', 'bar', '5.00', '', '', False),
    ('Fernet Branca', 'Liquori', 'bar', '6.00', '', '', False),
    ('Fernet Menta', 'Liquori', 'bar', '6.00', '', '', False),
    ('Fieno Grappa', 'Liquori', 'bar', '6.00', '', '', False),
    ('Ginepro', 'Liquori', 'bar', '5.00', '', '', False),
    ('Jack Daniels', 'Liquori', 'bar', '7.00', '', '', False),
    ('Jagermeister', 'Liquori', 'bar', '6.00', '', '', False),
    ('Limoncino', 'Liquori', 'bar', '5.00', '', '', False),
    ('Mela Verde', 'Liquori', 'bar', '5.00', '', '', False),
    ('Mirtillo', 'Liquori', 'bar', '5.00', '', '', False),
    ('Montenegro', 'Liquori', 'bar', '6.00', '', '', False),
    ('Moscato', 'Liquori', 'bar', '6.00', '', '', False),
    ('Mugo', 'Liquori', 'bar', '5.00', '', '', False),
    ('Pera Williams', 'Liquori', 'bar', '5.00', '', '', False),
    ('Ramazzotti', 'Liquori', 'bar', '6.00', '', '', False),
    ('Sambuca', 'Liquori', 'bar', '6.00', '', '', False),
    ('Teroldego Grappa', 'Liquori', 'bar', '5.00', '', '', False),
    ('Vodka', 'Liquori', 'bar', '5.00', '', '', False),
    ('Chardonnay MG', 'Vino', 'bar', '33.00', '', '', False),
    ('Lagrein Stella Alpina', 'Vino', 'bar', '38.00', '', '', False),
    ('Marzemino Trentino DOC', 'Vino', 'bar', '35.00', '', '', False),
    ('Morus Brut Millesimato', 'Vino', 'bar', '52.00', '', '', False),
    ('Morus Brut Rosé', 'Vino', 'bar', '60.00', '', '', False),
    ('Naonis Jader', 'Vino', 'bar', '5.00', '', '', False),
    ('Nosiola', 'Vino', 'bar', '6.00', '', '', False),
    ('Nosiola Poli Giovanni', 'Vino', 'bar', '34.00', '', '', False),
    ('Pinot Bianco', 'Vino', 'bar', '6.00', '', '', False),
    ('Pinot Bianco Muri Gries', 'Vino', 'bar', '32.00', '', '', False),
    ('Pinot Grigio Cantina Muri Gries', 'Vino', 'bar', '6.50', '', '', False),
    ('Pinot Grigio MG', 'Vino', 'bar', '32.00', '', '', False),
    ('Pinot Nero MG', 'Vino', 'bar', '40.00', '', '', False),
    ('Teroldego Vigneti delle Dolomiti', 'Vino', 'bar', '35.00', '', '', False),
]


def reset_menu(apps, schema_editor):
    MenuItem = apps.get_model("core", "MenuItem")
    # Anything already in the DB starts inactive; only the items below that are
    # flagged active come back on the list.
    MenuItem.objects.update(is_available=False)
    for name, category, station, price, description, composition, is_available in ITEMS:
        obj = MenuItem.objects.filter(
            name=name, category=category, station=station
        ).first()
        fields = dict(
            price=Decimal(price),
            description=description,
            composition=composition,
            is_available=is_available,
        )
        if obj is None:
            MenuItem.objects.create(name=name, category=category, station=station, **fields)
        else:
            for f, v in fields.items():
                setattr(obj, f, v)
            obj.save(update_fields=list(fields.keys()) + ["updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_employee_capabilities"),
    ]
    operations = [
        migrations.RunPython(reset_menu, migrations.RunPython.noop),
    ]
