from decimal import Decimal

from django.db import migrations


# (name, description, price, category, station, composition, is_available)
# Full Sissi menu from the owner's list. The 104 core items are is_available=True
# (active); the rest are is_available=False until staff switch them on.
ITEMS = [
    ('Espresso', '', '1.50', 'Caffetteria', 'bar', '', True),
    ('Decaffeinato', '', '2.00', 'Caffetteria', 'bar', '', True),
    ('Americano', '', '2.00', 'Caffetteria', 'bar', '', True),
    ('Corretto', '', '3.00', 'Caffetteria', 'bar', '', True),
    ('Caffè con panna', '', '2.50', 'Caffetteria', 'bar', '', True),
    ('Cappuccino', '', '3.00', 'Caffetteria', 'bar', '', True),
    ('Cappuccino con miele e cannella', '', '4.00', 'Caffetteria', 'bar', '', True),
    ('Latte bianco', '', '2.00', 'Caffetteria', 'bar', '', True),
    ('Latte macchiato', '', '3.50', 'Caffetteria', 'bar', '', True),
    ('Bombardino', '', '5.00', 'Caffetteria', 'bar', '', True),
    ('Punch', '', '5.00', 'Caffetteria', 'bar', '', True),
    ('Vin brulè', '', '6.00', 'Caffetteria', 'bar', '', True),
    ('Cioccolata calda con panna', '', '6.00', 'Caffetteria', 'bar', '', True),
    ('Orzo/Ginseng piccolo', '', '2.00', 'Caffetteria', 'bar', '', True),
    ('Orzo/Ginseng grande', '', '3.00', 'Caffetteria', 'bar', '', True),
    ('Flat White', '', '5.00', 'Caffetteria', 'bar', '', True),
    ('Tè/Tisana', '', '3.50', 'Caffetteria', 'bar', '', True),
    ('Acqua 0,5 l', '', '2.50', 'Bibite', 'bar', '', True),
    ('Succo di frutta', '', '4.00', 'Bibite', 'bar', '', True),
    ('Tè freddo', '', '4.00', 'Bibite', 'bar', '', True),
    ('Coca-Cola/Sprite', '', '4.50', 'Bibite', 'bar', '', True),
    ('Lemonsoda/Aranciata', '', '4.50', 'Bibite', 'bar', '', True),
    ('Limonata/Chinotto', '', '4.50', 'Bibite', 'bar', '', True),
    ("Spremuta d'arancia", '', '6.00', 'Bibite', 'bar', '', True),
    ('Tonica/Cedrata', '', '4.50', 'Bibite', 'bar', '', True),
    ('Kronenbourg 1664 alla spina 0,25 l', '', '4.00', 'Birra', 'bar', '', True),
    ('Kronenbourg 1664 alla spina 0,5 l', '', '7.00', 'Birra', 'bar', '', True),
    ('Birra in bottiglia 0,33 l', '', '5.00', 'Birra', 'bar', '', True),
    ('Peroni Gran Riserva Doppio Malto 0,5 l', '', '7.50', 'Birra', 'bar', '', True),
    ('Pinot grigio', 'Calice. Bottiglia: €33.', '6.00', 'Vino al calice e bottiglie', 'bar', '', True),
    ('Lugana', 'Calice. Bottiglia: €33.', '6.00', 'Vino al calice e bottiglie', 'bar', '', True),
    ('Gewürztraminer', 'Calice. Bottiglia: €33.', '6.00', 'Vino al calice e bottiglie', 'bar', '', True),
    ('Lagrein', 'Calice. Bottiglia: €35.', '6.00', 'Vino al calice e bottiglie', 'bar', '', True),
    ('Marzemino', 'Calice. Bottiglia: €35.', '6.00', 'Vino al calice e bottiglie', 'bar', '', True),
    ('Teroldego', 'Calice. Bottiglia: €35.', '6.00', 'Vino al calice e bottiglie', 'bar', '', True),
    ('Prosecco Valdobbiadene', 'Calice. Bottiglia: €33.', '6.00', 'Vino al calice e bottiglie', 'bar', '', True),
    ('Trento DOC', 'Calice. Bottiglia: €52.', '8.00', 'Vino al calice e bottiglie', 'bar', '', True),
    ('Croissant o krapfen', '', '2.50', 'Colazione', 'kitchen', 'Crema, marmellata, Nutella o pistacchio', True),
    ('Croissant vegano', '', '3.00', 'Colazione', 'kitchen', '', True),
    ('Biscotto Occhio di Bue', '', '3.70', 'Colazione', 'kitchen', 'Marmellata o Nutella', True),
    ('Crêpe con Nutella o miele', '', '7.00', 'Colazione', 'kitchen', '', True),
    ('French Toast con miele e noci', '', '13.00', 'Colazione', 'kitchen', '', True),
    ('Toast classico cotto e formaggio', '', '7.00', 'Colazione', 'kitchen', '', True),
    ('Baby Toast', '', '6.00', 'Colazione', 'kitchen', '', True),
    ('Omelette cotto e fontina', '', '13.00', 'Colazione', 'kitchen', '', True),
    ('Pan carré tostato', '', '13.00', 'Colazione', 'kitchen', '', True),
    ('Crêpe cotto e fontina', '', '8.00', 'Colazione', 'kitchen', '', True),
    ("Uovo all'occhio di bue", '', '13.00', 'Colazione', 'kitchen', 'Bacon e pan carré tostato', True),
    ('Aperol Spritz', '', '8.00', 'Aperitivi', 'bar', '', True),
    ('Limoncello Spritz', '', '10.00', 'Aperitivi', 'bar', '', True),
    ('Campari Soda', '', '6.00', 'Aperitivi', 'bar', '', True),
    ('Americano/Negroni', '', '10.00', 'Aperitivi', 'bar', '', True),
    ('Negroni Sbagliato/Negrosky', '', '10.00', 'Aperitivi', 'bar', '', True),
    ('Daiquiri/Mimosa', '', '10.00', 'Aperitivi', 'bar', '', True),
    ('Campari Shakerato', '', '7.00', 'Aperitivi', 'bar', '', True),
    ('Patatine fritte', '', '5.50', 'Da stuzzicare', 'kitchen', '', True),
    ('Sticks misti da stuzzicare', '', '25.00', 'Da stuzzicare', 'kitchen', 'Sticks di polenta, rosti di patate, speck, lardo, miele, formaggio e noci', True),
    ('Crodino/San Bitter', '', '6.00', 'Analcolici', 'bar', '', True),
    ('Lurisia Assenzio o Genziana', '', '6.00', 'Analcolici', 'bar', '', True),
    ('Succo di pomodoro condito', '', '6.00', 'Analcolici', 'bar', '', True),
    ('Analcolico Sissi', '', '8.00', 'Analcolici', 'bar', '', True),
    ('Bloody Mary', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Moscow Mule', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Margarita', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Caipiroska/Caipirinha', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Cosmopolitan', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Cuba Libre', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Sex on the Beach', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Long Island Iced Tea', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Tequila Sunrise', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Vodka Tonic', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Sissi Signature Cocktail', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Gin Tonic Base Bombay', '', '12.00', 'Cocktails', 'bar', '', True),
    ('Premium Cocktails', '', '14.00', 'Cocktails', 'bar', '', True),
    ('Tortel di patate con la Caprese', '', '14.00', 'Cucina di Sissi', 'kitchen', '', True),
    ('Tortel di patate con lardo e miele', '', '16.00', 'Cucina di Sissi', 'kitchen', '', True),
    ('Tortel di patate con uova e bacon', '', '16.00', 'Cucina di Sissi', 'kitchen', '', True),
    ('Tortel di patate con salsiccia', '', '18.00', 'Cucina di Sissi', 'kitchen', 'Formaggio alla piastra e crauti', True),
    ('Cotoletta con patatine fritte', '', '16.00', 'Cucina di Sissi', 'kitchen', '', True),
    ('Patatine fritte', '', '5.50', 'Cucina di Sissi', 'kitchen', '', True),
    ('Bocconcino Sissi', '', '12.00', 'Panini', 'kitchen', 'Würstel, ketchup e cipolla caramellata', True),
    ('Hot Dog Alpino', '', '12.00', 'Panini', 'kitchen', 'Würstel, senape e crauti', True),
    ('Tirolese', '', '12.00', 'Panini', 'kitchen', 'Würstel, maionese e cipolla fritta', True),
    ('Montantaro', '', '12.00', 'Panini', 'kitchen', 'Porchetta, insalata, salsa tartara e cipolla fritta', True),
    ('Rendena', '', '8.50', 'Panini', 'kitchen', 'Speck, formaggio Casolet e salsa tartara', True),
    ('Snowboard', '', '13.00', 'Panini', 'kitchen', 'Cotoletta, maionese, pomodorino, insalata e cipolla fritta', True),
    ('Vegetariano', '', '8.00', 'Panini', 'kitchen', 'Mozzarella e pomodoro', True),
    ('Burgherita Sissi', 'Extra: uovo, bacon, cetriolini, cipolla fritta o caramellata + €1.50', '14.00', 'Panini', 'kitchen', 'Burger bun, hamburger di manzo, cheddar, pomodoro, insalata e salsa', True),
    ('Hamburger vegetariano', '', '14.00', 'Panini', 'kitchen', 'Burger bun, burger ai vegetali grigliati, scamorza, pomodoro, insalata, cipolla fritta e salsa', True),
    ('Sissi Club Sandwich', '', '8.00', 'Spuntino Salato', 'kitchen', 'Tacchino, pomodoro, maionese e insalata', True),
    ('Toast vegetariano', '', '7.00', 'Spuntino Salato', 'kitchen', 'Fontina, pomodoro e insalata', True),
    ('Piadina cotto', '', '8.00', 'Spuntino Salato', 'kitchen', 'Formaggio, pomodoro e insalata', True),
    ('Piadina speck', '', '8.80', 'Spuntino Salato', 'kitchen', 'Brie, miele, noci e rucola', True),
    ('Crostata del giorno', '', '5.00', 'Dolci', 'kitchen', '', True),
    ('Crostata vegana', '', '5.50', 'Dolci', 'kitchen', '', True),
    ('Strüdel di mele', '', '6.50', 'Dolci', 'kitchen', 'Salsa di vaniglia e panna', True),
    ('Sacher con la panna', '', '6.50', 'Dolci', 'kitchen', '', True),
    ('Torta di carote con la panna', '', '6.50', 'Dolci', 'kitchen', '', True),
    ('Torta di carote con gelato', '', '7.00', 'Dolci', 'kitchen', '', True),
    ('Cheesecake Sissi', '', '7.00', 'Dolci', 'kitchen', '', True),
    ('Crêpes con Nutella', '', '7.00', 'Dolci', 'kitchen', '', True),
    ('Grappe e liquori', '', '5.00', 'Grappe e liquori', 'bar', '', True),
    ('Grappa Barricata / 18 lune', '', '6.00', 'Grappe e liquori', 'bar', '', True),
    ('Amari', '', '6.00', 'Grappe e liquori', 'bar', '', True),
    ('Caffè Shakerato', '', '5.00', 'Caffetteria', 'bar', '', False),
    ('Camomilla', '', '3.00', 'Caffetteria', 'bar', '', False),
    ('Cappuccino Deca', '', '3.50', 'Caffetteria', 'bar', '', False),
    ('Cappuccino Panna', '', '5.00', 'Caffetteria', 'bar', '', False),
    ('Cappuccino Soya', '', '3.50', 'Caffetteria', 'bar', '', False),
    ('Cappuccio Orzo', '', '3.50', 'Caffetteria', 'bar', '', False),
    ('Cioccolata Arancia Cannella', '', '7.00', 'Caffetteria', 'bar', '', False),
    ('Cioccolata Baby', '', '3.00', 'Caffetteria', 'bar', '', False),
    ('Cioccolata Bianca Menta', '', '6.50', 'Caffetteria', 'bar', '', False),
    ('Cioccolata Calda', '', '5.50', 'Caffetteria', 'bar', '', False),
    ('Cioccolata Calda Bianca', '', '5.50', 'Caffetteria', 'bar', '', False),
    ('Cioccolata Cocco Mou', '', '7.00', 'Caffetteria', 'bar', '', False),
    ('Cioccolata Peperoncino', '', '7.00', 'Caffetteria', 'bar', '', False),
    ('Deca Macchiato', '', '2.00', 'Caffetteria', 'bar', '', False),
    ('Deca Macchiato Freddo', '', '2.00', 'Caffetteria', 'bar', '', False),
    ('Doppio Caffè', '', '3.00', 'Caffetteria', 'bar', '', False),
    ('Ginseng Grande', '', '3.00', 'Caffetteria', 'bar', '', False),
    ('Ginseng Piccolo', '', '2.50', 'Caffetteria', 'bar', '', False),
    ('Latte Caldo', '', '2.00', 'Caffetteria', 'bar', '', False),
    ('Lungo Caffè', '', '1.50', 'Caffetteria', 'bar', '', False),
    ('Macchiato', '', '1.50', 'Caffetteria', 'bar', '', False),
    ('Macchiato Freddo', '', '1.50', 'Caffetteria', 'bar', '', False),
    ('Macchiatone', '', '2.00', 'Caffetteria', 'bar', '', False),
    ('Marocchino', '', '2.50', 'Caffetteria', 'bar', '', False),
    ('No Lattosio Cappuccio', '', '3.00', 'Caffetteria', 'bar', '', False),
    ('Orzo Grande', '', '3.00', 'Caffetteria', 'bar', '', False),
    ('Orzo Macchiato', '', '2.50', 'Caffetteria', 'bar', '', False),
    ('Orzo Piccolo', '', '2.50', 'Caffetteria', 'bar', '', False),
    ('Punch Mandarino', '', '5.00', 'Caffetteria', 'bar', '', False),
    ('Ristretto', '', '1.50', 'Caffetteria', 'bar', '', False),
    ('Schiumetta Piccola', '', '1.50', 'Caffetteria', 'bar', '', False),
    ('Schiumetta', '', '1.50', 'Caffetteria', 'bar', '', False),
    ('Limonata', '', '4.50', 'Bevande', 'bar', '', False),
    ('ACE Succo', '', '4.00', 'Bevande', 'bar', '', False),
    ('Acqua 0,5 Frizz Pejo', '', '2.50', 'Bevande', 'bar', '', False),
    ('Acqua 0,5 Nat. Pejo', '', '2.50', 'Bevande', 'bar', '', False),
    ('Acqua 0,5 Asporto', '', '2.00', 'Bevande', 'bar', '', False),
    ('Acqua 1 L Pejo', '', '4.00', 'Bevande', 'bar', '', False),
    ('Acqua 1 Litro Asporto', '', '3.50', 'Bevande', 'bar', '', False),
    ('Acqua Menta Lampone', '', '3.00', 'Bevande', 'bar', '', False),
    ('Albicocca Succo', '', '4.00', 'Bevande', 'bar', '', False),
    ('Ananas Succo', '', '4.00', 'Bevande', 'bar', '', False),
    ('Aranciata', '', '4.50', 'Bevande', 'bar', '', False),
    ('Bicchiere H2O', '', '0.50', 'Bevande', 'bar', '', False),
    ('Bicchiere H2O Frizzante', '', '0.50', 'Bevande', 'bar', '', False),
    ('Cedrata', '', '4.50', 'Bevande', 'bar', '', False),
    ('Chinotto', '', '4.50', 'Bevande', 'bar', '', False),
    ('Coca Cola', '', '4.50', 'Bevande', 'bar', '', False),
    ('Coca Zero', '', '4.50', 'Bevande', 'bar', '', False),
    ('Crodino', '', '6.00', 'Bevande', 'bar', '', False),
    ('Energy Drink', '', '4.50', 'Bevande', 'bar', '', False),
    ('Lemonsoda', '', '4.50', 'Bevande', 'bar', '', False),
    ('Let It Snow', '', '11.50', 'Bevande', 'bar', '', False),
    ('Mela Succo', '', '4.00', 'Bevande', 'bar', '', False),
    ('Milkshake', '', '7.00', 'Bevande', 'bar', '', False),
    ('Mirtillo Succo', '', '4.00', 'Bevande', 'bar', '', False),
    ('Pera Succo', '', '4.00', 'Bevande', 'bar', '', False),
    ('Pesca Succo', '', '4.00', 'Bevande', 'bar', '', False),
    ('Red Bull', '', '6.00', 'Bevande', 'bar', '', False),
    ('Sanbitter', '', '6.00', 'Bevande', 'bar', '', False),
    ('Sissi Mocktail', '', '11.50', 'Bevande', 'bar', '', False),
    ('Sprite', '', '4.50', 'Bevande', 'bar', '', False),
    ('Succo Pomodoro', '', '4.00', 'Bevande', 'bar', '', False),
    ('Tè Limone', '', '4.00', 'Bevande', 'bar', '', False),
    ('Tè Pesca', '', '4.00', 'Bevande', 'bar', '', False),
    ('Amaro del Capo', '', '6.00', 'Liquori', 'bar', '', False),
    ('Amaro Trentino', '', '6.00', 'Liquori', 'bar', '', False),
    ('Anima Nera', '', '5.00', 'Liquori', 'bar', '', False),
    ('Asperula', '', '5.00', 'Liquori', 'bar', '', False),
    ('Averna', '', '6.00', 'Liquori', 'bar', '', False),
    ('Baileys', '', '6.00', 'Liquori', 'bar', '', False),
    ('Barricata', '', '6.00', 'Liquori', 'bar', '', False),
    ('Braulio', '', '6.00', 'Liquori', 'bar', '', False),
    ('Cacao Nocciola', '', '6.00', 'Liquori', 'bar', '', False),
    ('Camomilla Grappa', '', '5.00', 'Liquori', 'bar', '', False),
    ('Caramello Salato', '', '6.00', 'Liquori', 'bar', '', False),
    ('Cirmolo', '', '5.00', 'Liquori', 'bar', '', False),
    ('Cointreau', '', '5.00', 'Liquori', 'bar', '', False),
    ('Fernet Branca', '', '6.00', 'Liquori', 'bar', '', False),
    ('Fernet Menta', '', '6.00', 'Liquori', 'bar', '', False),
    ('Fieno Grappa', '', '6.00', 'Liquori', 'bar', '', False),
    ('Ginepro', '', '5.00', 'Liquori', 'bar', '', False),
    ('Jack Daniels', '', '7.00', 'Liquori', 'bar', '', False),
    ('Jagermeister', '', '6.00', 'Liquori', 'bar', '', False),
    ('Limoncino', '', '5.00', 'Liquori', 'bar', '', False),
    ('Mela Verde', '', '5.00', 'Liquori', 'bar', '', False),
    ('Mirtillo', '', '5.00', 'Liquori', 'bar', '', False),
    ('Montenegro', '', '6.00', 'Liquori', 'bar', '', False),
    ('Moscato', '', '6.00', 'Liquori', 'bar', '', False),
    ('Mugo', '', '5.00', 'Liquori', 'bar', '', False),
    ('Pera Williams', '', '5.00', 'Liquori', 'bar', '', False),
    ('Ramazzotti', '', '6.00', 'Liquori', 'bar', '', False),
    ('Sambuca', '', '6.00', 'Liquori', 'bar', '', False),
    ('Teroldego Grappa', '', '5.00', 'Liquori', 'bar', '', False),
    ('Vodka', '', '5.00', 'Liquori', 'bar', '', False),
    ('Chardonnay MG', '', '33.00', 'Vino', 'bar', '', False),
    ('Lagrein Stella Alpina', '', '38.00', 'Vino', 'bar', '', False),
    ('Marzemino Trentino DOC', '', '35.00', 'Vino', 'bar', '', False),
    ('Morus Brut Millesimato', '', '52.00', 'Vino', 'bar', '', False),
    ('Morus Brut Rosé', '', '60.00', 'Vino', 'bar', '', False),
    ('Naonis Jader', '', '5.00', 'Vino', 'bar', '', False),
    ('Nosiola', '', '6.00', 'Vino', 'bar', '', False),
    ('Nosiola Poli Giovanni', '', '34.00', 'Vino', 'bar', '', False),
    ('Pinot Bianco', '', '6.00', 'Vino', 'bar', '', False),
    ('Pinot Bianco Muri Gries', '', '32.00', 'Vino', 'bar', '', False),
    ('Pinot Grigio MG', '', '32.00', 'Vino', 'bar', '', False),
    ('Pinot Grigio Cantina Muri Gries', '', '6.50', 'Vino', 'bar', '', False),
    ('Pinot Nero MG', '', '40.00', 'Vino', 'bar', '', False),
    ('Teroldego Vigneti delle Dolomiti', '', '35.00', 'Vino', 'bar', '', False),
    ('Gelato 1 Chilo', '', '24.00', 'Gelati', 'kitchen', '', False),
    ('Gelato 500 g', '', '12.00', 'Gelati', 'kitchen', '', False),
    ('2 Gusti Take Away', '', '3.50', 'Gelati', 'kitchen', '', False),
    ('Affogato al Caffè', '', '4.00', 'Gelati', 'kitchen', '', False),
    ('Affogato Baileys', '', '10.00', 'Gelati', 'kitchen', '', False),
    ('Cono Coppetta 1', '', '2.00', 'Gelati', 'kitchen', '', False),
    ('Cono Coppetta 2', '', '3.50', 'Gelati', 'kitchen', '', False),
    ('Cono Coppetta 3', '', '4.50', 'Gelati', 'kitchen', '', False),
    ('Coppa 1', '', '3.50', 'Gelati', 'kitchen', '', False),
    ('Coppa 2', '', '5.00', 'Gelati', 'kitchen', '', False),
    ('Coppa 3', '', '6.50', 'Gelati', 'kitchen', '', False),
    ('Frappè', '', '8.50', 'Gelati', 'kitchen', '', False),
    ('Jingle Bell Rock', '', '11.50', 'Gelati', 'kitchen', '', False),
    ('Panino Speck', '', '8.50', 'Food', 'kitchen', '', False),
    ('Piadina Light', '', '8.50', 'Food', 'kitchen', '', False),
    ('Piadina Salame', '', '8.50', 'Food', 'kitchen', '', False),
    ('Piadina Vegetariana', '', '8.00', 'Food', 'kitchen', '', False),
    ('Tortel Lardo o Speck', '', '16.00', 'Food', 'kitchen', '', False),
    ('Tortel Uova', '', '16.00', 'Food', 'kitchen', '', False),
    ('Fagottino Mela', '', '3.50', 'Dolci', 'kitchen', '', False),
    ('Fetta Crostata Asporto', '', '4.00', 'Dolci', 'kitchen', '', False),
    ('Fetta Sacher Asporto', '', '5.50', 'Dolci', 'kitchen', '', False),
    ('Fetta Strudel Asporto', '', '5.50', 'Dolci', 'kitchen', '', False),
    ('Gluten Free Snack', '', '3.00', 'Dolci', 'kitchen', '', False),
    ('Krapfen Crema', '', '2.50', 'Dolci', 'kitchen', '', False),
    ('Krapfen Marmellata', '', '2.50', 'Dolci', 'kitchen', '', False),
    ('Krapfen Nutella', '', '2.50', 'Dolci', 'kitchen', '', False),
    ('Krapfen Pistacchio', '', '3.00', 'Dolci', 'kitchen', '', False),
    ('Krapfen Vuoto', '', '2.50', 'Dolci', 'kitchen', '', False),
    ('Lintz', '', '6.50', 'Dolci', 'kitchen', '', False),
    ('Macarons', '', '2.00', 'Dolci', 'kitchen', '', False),
    ('Marshmallow Piccolo', '', '0.50', 'Dolci', 'kitchen', '', False),
    ('Meringa', '', '1.50', 'Dolci', 'kitchen', '', False),
    ('Mignon Pasticcini', '', '1.50', 'Dolci', 'kitchen', '', False),
    ('Mini Sacherina', '', '2.50', 'Dolci', 'kitchen', '', False),
    ('Muffin', '', '3.80', 'Dolci', 'kitchen', '', False),
    ('Occhio Bue Cioccolato', '', '3.70', 'Dolci', 'kitchen', '', False),
    ('Occhio di Bue Marmellata', '', '3.70', 'Dolci', 'kitchen', '', False),
    ('Sacher', '', '6.50', 'Dolci', 'kitchen', '', False),
    ('Senza Glutine Senza Lattosio', '', '12.00', 'Dolci', 'kitchen', '', False),
    ('Sissi Souvenir', '', '5.90', 'Dolci', 'kitchen', '', False),
    ('Strudel Piccolo', '', '18.50', 'Dolci', 'kitchen', '', False),
    ('Strudel + Vaniglia Gelato', '', '7.50', 'Dolci', 'kitchen', '', False),
    ('Torta di Carote', '', '6.00', 'Dolci', 'kitchen', '', False),
    ('Mele Torta', '', '6.50', 'Dolci', 'kitchen', '', False),
    ('Aperitivo Assenzio Lurisia', '', '6.00', 'Aperitivi', 'bar', '', False),
    ('Aurora Boreale', '', '14.00', 'Aperitivi', 'bar', '', False),
    ("Baby It's Cold", '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Bloody Virgin', '', '6.00', 'Aperitivi', 'bar', '', False),
    ('Cinnamon Snow Mule', '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Coconut Snowdrift', '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Frosted Maracuja', '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Gingerbread Martini', '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Marshmallow Martini', '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Merry Kiss Shot', '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Mr Sandman', '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Snowflake', '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Spritz Misto', '', '8.00', 'Aperitivi', 'bar', '', False),
    ('Americano', '', '10.00', 'Aperitivi', 'bar', '', False),
    ('Lavender Spritz', '', '12.00', 'Aperitivi', 'bar', '', False),
    ('Analcolico Frutta', '', '8.00', 'Aperitivi', 'bar', '', False),
    ('Aperitivo Lurisia Genziana', '', '6.00', 'Aperitivi', 'bar', '', False),
    ('Cocktail 12€ Base', '', '12.00', 'Aperitivi', 'bar', '', False),
    ('Forst', '', '5.00', 'Aperitivi', 'bar', '', False),
    ('Gin Tonic 12€ Base', '', '12.00', 'Aperitivi', 'bar', '', False),
    ('Hugo', '', '8.00', 'Aperitivi', 'bar', '', False),
    ('Martini', '', '6.00', 'Aperitivi', 'bar', '', False),
    ('Media Grimbergen', '', '8.00', 'Aperitivi', 'bar', '', False),
    ('Media Kronenbourg', '', '7.00', 'Aperitivi', 'bar', '', False),
    ('Negroni', '', '10.00', 'Aperitivi', 'bar', '', False),
    ('Negrosky', '', '10.00', 'Aperitivi', 'bar', '', False),
    ('Franz Joseph Spritz', '', '14.00', 'Aperitivi', 'bar', '', False),
    ('Spritz Estivo', '', '12.00', 'Aperitivi', 'bar', '', False),
    ('Piccola Kronenbourg', '', '4.00', 'Aperitivi', 'bar', '', False),
    ('Radler Media', '', '7.00', 'Aperitivi', 'bar', '', False),
    ('Radler Piccola', '', '4.00', 'Aperitivi', 'bar', '', False),
]


def reload_menu(apps, schema_editor):
    MenuItem = apps.get_model("core", "MenuItem")
    Order = apps.get_model("core", "Order")
    Table = apps.get_model("core", "Table")

    # Order delete cascades OrderItem + OrderEvent (the order history); removing
    # the OrderItems is what frees the PROTECT on MenuItem so it can be replaced.
    Order.objects.all().delete()

    # No orders remain, so free every table (clear the visit state).
    Table.objects.all().update(
        status="free",
        guest_count=0,
        opened_at=None,
        attention="",
        attention_reason="",
        attention_acknowledged=False,
    )

    MenuItem.objects.all().delete()
    MenuItem.objects.bulk_create([
        MenuItem(
            name=n, description=d, price=Decimal(p), category=c, image_url="",
            station=s, tags=[], composition=comp, allergens=[], is_available=av,
            is_promoted=False, preparation_minutes=5, portion_weight="", calories=None,
        )
        for (n, d, p, c, s, comp, av) in ITEMS
    ])


def noop(apps, schema_editor):
    # One-way data reset; nothing to undo.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_archive_unavailable_menu_items"),
    ]

    operations = [
        migrations.RunPython(reload_menu, noop),
    ]
