# Generated by Django 5.2.15 on 2026-07-15 14:02

import apps.core.media_storage
import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_normalize_sissi_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='default', max_length=40, unique=True)),
                ('name', models.CharField(default='Caffè & Bistrò Sissi', max_length=120)),
                ('tagline', models.CharField(default='Café, bistro and bar in Madonna di Campiglio', max_length=200)),
                ('tagline_it', models.CharField(default='Caffè, bistrot e bar a Madonna di Campiglio', max_length=200)),
                ('about', models.TextField(default='A warm mountain bistro for coffee, aperitifs, cocktails, sandwiches, sweet treats and quick dishes from the Sissi menu.')),
                ('about_it', models.TextField(default='Un bistrot di montagna per caffetteria, aperitivi, cocktail, panini, dolci e piatti veloci dal menu Sissi.')),
                ('address', models.CharField(default='Madonna di Campiglio · Trentino', max_length=200)),
                ('address_it', models.CharField(default='Madonna di Campiglio · Trentino', max_length=200)),
                ('hours', models.CharField(default="Ask staff for today's hours", max_length=200)),
                ('hours_it', models.CharField(default='Chiedi allo staff gli orari di oggi', max_length=200)),
                ('badges', models.JSONField(blank=True, default=apps.core.models._default_badges)),
                ('maps_url', models.URLField(blank=True, default='https://maps.app.goo.gl/L8UMd16ZXUTk5Jx28', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, storage=apps.core.media_storage.venue_media_storage, upload_to=apps.core.media_storage.venue_image_path)),
                ('cover', models.ImageField(blank=True, null=True, storage=apps.core.media_storage.venue_media_storage, upload_to=apps.core.media_storage.venue_image_path)),
                ('color_bg', models.CharField(default='#f2efe8', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB (e.g. #C8821E).', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_card', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB (e.g. #C8821E).', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_ink', models.CharField(default='#1e1b16', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB (e.g. #C8821E).', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_mut', models.CharField(default='#8b8377', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB (e.g. #C8821E).', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_line', models.CharField(default='#e7e2d8', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB (e.g. #C8821E).', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_accent', models.CharField(default='#c8821e', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB (e.g. #C8821E).', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_accent_deep', models.CharField(default='#9a6310', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB (e.g. #C8821E).', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_accent_soft', models.CharField(default='#f1e2c8', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB (e.g. #C8821E).', regex='^#[0-9a-fA-F]{6}$')])),
                ('storefront_blocks', models.JSONField(blank=True, default=apps.core.models._default_storefront_blocks)),
                ('pinned_posts_limit', models.PositiveSmallIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'venue settings',
                'db_table': 'cafe_venue_settings',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='can_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('admin', 'Admin'), ('smm', 'SMM')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('threads', 'Threads'), ('twitter_x', 'X (Twitter)'), ('facebook', 'Facebook')], db_index=True, max_length=24)),
                ('embed_html', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='core.employee')),
            ],
            options={
                'db_table': 'cafe_social_posts',
                'ordering': ['-is_pinned', '-pinned_at', '-id'],
                'indexes': [models.Index(fields=['is_hidden', '-is_pinned', '-id'], name='socialpost_feed_idx')],
            },
        ),
    ]
