# Generated by Django 5.2.15 on 2026-07-16 18:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_seed_venue_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_grant_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CouponCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('title_it', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_it', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source_utm', models.SlugField(blank=True, max_length=64)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_total_issues', models.PositiveIntegerField(blank=True, null=True)),
                ('per_wallet_limit', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_campaigns', to='core.employee')),
            ],
            options={
                'db_table': 'cafe_coupon_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestWallet',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafe_guest_wallets',
            },
        ),
        migrations.CreateModel(
            name='IssuedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('void', 'Void')], db_index=True, default='active', max_length=16)),
                ('issued_via', models.CharField(choices=[('staff_qr', 'Staff QR'), ('campaign_link', 'Campaign link')], max_length=24)),
                ('utm_source', models.CharField(blank=True, max_length=64)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.couponcampaign')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_coupons', to='core.employee')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_coupons', to='core.order')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_coupons', to='core.employee')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.guestwallet')),
            ],
            options={
                'db_table': 'cafe_issued_coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_order', to='core.issuedcoupon'),
        ),
        migrations.AddIndex(
            model_name='issuedcoupon',
            index=models.Index(fields=['wallet', 'status', '-created_at'], name='coupon_wallet_status_idx'),
        ),
    ]
