# Generated by Django 5.2.15 on 2026-07-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_coupons_wallets_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentionsignal',
            name='alert_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='alert_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core.employee')),
            ],
            options={
                'db_table': 'cafe_push_subscriptions',
            },
        ),
    ]
