# Generated by Django 5.2.16 on 2026-07-18 11:00

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_sissy_and_tasks(apps, schema_editor):
    Restaurant = apps.get_model("core", "Restaurant")
    VenueSettings = apps.get_model("core", "VenueSettings")
    StaffTask = apps.get_model("core", "StaffTask")

    restaurant, _ = Restaurant.objects.get_or_create(
        slug="sissy-bar", defaults={"name": "Caffè & Bistrò Sissi"}
    )
    VenueSettings.objects.filter(restaurant=restaurant, slug="default").update(
        slug="sissy-bar"
    )
    StaffTask.objects.filter(status="open", assignee__isnull=True).update(
        status="available"
    )
    StaffTask.objects.filter(status="open", assignee__isnull=False).update(
        status="in_progress"
    )


def reverse_normalize_tasks(apps, schema_editor):
    StaffTask = apps.get_model("core", "StaffTask")
    StaffTask.objects.filter(status__in=["available", "in_progress"]).update(
        status="open"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_seed_checklists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('timezone', models.CharField(default='Europe/Rome', max_length=64)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('legacy_slugs', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafe_restaurants',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='can_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_shift_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='botjobrun',
            name='job_key',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='key',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='couponcampaign',
            name='slug',
            field=models.SlugField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='key',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='staffpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_progress', 'In progress'), ('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venuesettings',
            name='slug',
            field=models.SlugField(default='sissy-bar', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='attentionsignal',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='attention_signals', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='botjobrun',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='bot_job_runs', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='botreminder',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='bot_reminders', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='chatreadmark',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_marks', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='couponcampaign',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_campaigns', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='guestwallet',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='guest_wallets', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='issuedcoupon',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='issued_coupons', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='staffpreference',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='staff_preferences', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='staff_tasks', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='venuesettings',
            name='restaurant',
            field=models.OneToOneField(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.restaurant'),
        ),
        migrations.RunPython(normalize_sissy_and_tasks, reverse_normalize_tasks),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status', '-created_at'], name='order_rest_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='botjobrun',
            constraint=models.UniqueConstraint(fields=('restaurant', 'job_key'), name='botjob_restaurant_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('restaurant', 'key'), name='checklist_restaurant_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaign',
            constraint=models.UniqueConstraint(fields=('restaurant', 'slug'), name='campaign_restaurant_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('restaurant', 'user'), name='employee_restaurant_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'key'), name='menu_category_restaurant_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='staffpreference',
            constraint=models.UniqueConstraint(fields=('restaurant', 'user'), name='staffpref_restaurant_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'number'), name='table_restaurant_number_unique'),
        ),
    ]
