# Generated by Django 5.2.15 on 2026-07-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alerts_push_escalation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_key', models.CharField(max_length=120, unique=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cafe_bot_job_runs',
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('title_it', models.CharField(blank=True, max_length=120)),
                ('task_category', models.CharField(choices=[('opening', 'Opening'), ('closing', 'Closing'), ('cleaning', 'Cleaning'), ('inventory', 'Inventory'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafe_checklist_templates',
            },
        ),
        migrations.AddField(
            model_name='venuesettings',
            name='closing_checklist_deadline',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuesettings',
            name='closing_checklist_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuesettings',
            name='opening_checklist_deadline',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuesettings',
            name='opening_checklist_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BotReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('general', 'General'), ('kitchen', 'Kitchen'), ('bar', 'Bar')], max_length=16)),
                ('text', models.CharField(max_length=300)),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_reminders', to='core.employee')),
            ],
            options={
                'db_table': 'cafe_bot_reminders',
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('text_it', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.checklisttemplate')),
            ],
            options={
                'db_table': 'cafe_checklist_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('opening', 'Opening'), ('closing', 'Closing'), ('cleaning', 'Cleaning'), ('inventory', 'Inventory'), ('service', 'Service'), ('other', 'Other')], db_index=True, default='other', max_length=24)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=16)),
                ('recurrence_weekdays', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('chat', 'Chat'), ('planner', 'Planner'), ('bot', 'Bot')], default='chat', max_length=16)),
                ('overdue_nudged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='core.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='core.employee')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_done', to='core.employee')),
                ('recurring_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.stafftask')),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_tasks', to='core.checklistitem')),
            ],
            options={
                'db_table': 'cafe_staff_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('general', 'General'), ('kitchen', 'Kitchen'), ('bar', 'Bar')], db_index=True, max_length=16)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('task', 'Task'), ('checklist', 'Checklist'), ('system', 'System')], default='text', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='core.employee')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.chatmessage')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.stafftask')),
            ],
            options={
                'db_table': 'cafe_chat_messages',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatReadMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('general', 'General'), ('kitchen', 'Kitchen'), ('bar', 'Bar')], max_length=16)),
                ('last_read_message_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_marks', to='core.employee')),
            ],
            options={
                'db_table': 'cafe_chat_read_marks',
                'constraints': [models.UniqueConstraint(fields=('employee', 'channel'), name='chat_read_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='stafftask',
            index=models.Index(fields=['status', 'due_at'], name='task_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['channel', '-id'], name='chat_channel_id_idx'),
        ),
    ]
