# Generated by Django 5.2.16 on 2026-07-18 11:16

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_restaurant_employee_can_manage_employee_can_reports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('taken', 'Taken'), ('left', 'Left'), ('reassigned', 'Reassigned'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('cancelled', 'Cancelled')], db_index=True, max_length=24)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_events', to='core.employee')),
                ('restaurant', models.ForeignKey(default=apps.core.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='task_events', to='core.restaurant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.stafftask')),
            ],
            options={
                'db_table': 'cafe_task_events',
                'ordering': ['created_at'],
            },
        ),
    ]
