from decimal import Decimal

CLIENT_MENU_TAG = "client"


# Owner POS/raw menu: staff sees every row. Rows tagged with CLIENT_MENU_TAG are
# the subset from the printed guest menu photos.
RAW_MENU = [
    ("Americano caffè", "2.00", "CAFFETTERIA"),
    ("Bombardino", "5.00", "CAFFETTERIA"),
    ("Caffè", "1.50", "CAFFETTERIA"),
    ("Caffè con panna", "2.50", "CAFFETTERIA"),
    ("Caffè shakerato", "5.00", "CAFFETTERIA"),
    ("Camomilla", "3.00", "CAFFETTERIA"),
    ("Cappuccino deca", "3.50", "CAFFETTERIA"),
    ("Cappuccino miele cannella", "4.00", "CAFFETTERIA"),
    ("Cappuccino panna", "5.00", "CAFFETTERIA"),
    ("Cappuccino soya", "3.50", "CAFFETTERIA"),
    ("Cappuccio orzo", "3.50", "CAFFETTERIA"),
    ("Cioccolata arancia cannella", "7.00", "CAFFETTERIA"),
    ("Cioccolata baby", "3.00", "CAFFETTERIA"),
    ("Cioccolata bianca menta", "6.50", "CAFFETTERIA"),
    ("Cioccolata calda", "5.50", "CAFFETTERIA"),
    ("Cioccolata calda bianca", "5.50", "CAFFETTERIA"),
    ("Cioccolata cocco/mou", "7.00", "CAFFETTERIA"),
    ("Cioccolata con panna", "6.00", "CAFFETTERIA"),
    ("Cioccolata peperoncino", "7.00", "CAFFETTERIA"),
    ("Corretto", "3.00", "CAFFETTERIA"),
    ("Deca macchiato", "2.00", "CAFFETTERIA"),
    ("Deca macchiato freddo", "2.00", "CAFFETTERIA"),
    ("Decaffeinato", "2.00", "CAFFETTERIA"),
    ("Doppio caffè", "3.00", "CAFFETTERIA"),
    ("Flat white", "5.00", "CAFFETTERIA"),
    ("Ginseng grande", "3.00", "CAFFETTERIA"),
    ("Ginseng piccolo", "2.50", "CAFFETTERIA"),
    ("Latte caldo", "2.00", "CAFFETTERIA"),
    ("Latte macchiato", "3.50", "CAFFETTERIA"),
    ("Lungo caffè", "1.50", "CAFFETTERIA"),
    ("Macchiato", "1.50", "CAFFETTERIA"),
    ("Macchiato freddo", "1.50", "CAFFETTERIA"),
    ("Macchiatone", "2.00", "CAFFETTERIA"),
    ("Marocchino", "2.50", "CAFFETTERIA"),
    ("No lattosio cappuccio", "3.00", "CAFFETTERIA"),
    ("Orzo grande", "3.00", "CAFFETTERIA"),
    ("Orzo macchiato", "2.50", "CAFFETTERIA"),
    ("Orzo piccolo", "2.50", "CAFFETTERIA"),
    ("Punch mandarino", "5.00", "CAFFETTERIA"),
    ("Ristretto", "1.50", "CAFFETTERIA"),
    ("Schiumetta", "1.50", "CAFFETTERIA"),
    ("Tè / tisana", "3.50", "CAFFETTERIA"),
    ("Vin brulè", "6.00", "CAFFETTERIA"),
    ("Cappuccino", "3.00", "CAFFETTERIA"),
    ("Limonata", "4.50", "BEVANDE"),
    ("ACE succo", "4.00", "BEVANDE"),
    ("Acqua 0,5 frizzante Pejo", "2.50", "BEVANDE"),
    ("Acqua 0,5 naturale Pejo", "2.50", "BEVANDE"),
    ("Acqua 0,5 asporto", "2.00", "BEVANDE"),
    ("Acqua 1 L Pejo", "4.00", "BEVANDE"),
    ("Acqua 1 litro asporto", "3.50", "BEVANDE"),
    ("Acqua menta lampone", "3.00", "BEVANDE"),
    ("Albicocca succo", "4.00", "BEVANDE"),
    ("Ananas succo", "4.00", "BEVANDE"),
    ("Aranciata", "4.50", "BEVANDE"),
    ("Bicchiere H2O", "0.50", "BEVANDE"),
    ("Bicchiere H2O frizzante", "0.50", "BEVANDE"),
    ("Campari soda", "6.00", "BEVANDE"),
    ("Cedrata", "4.50", "BEVANDE"),
    ("Chinotto", "4.50", "BEVANDE"),
    ("Coca Cola", "4.50", "BEVANDE"),
    ("Coca Zero", "4.50", "BEVANDE"),
    ("Crodino", "6.00", "BEVANDE"),
    ("Energy drink", "4.50", "BEVANDE"),
    ("Lemonsoda", "4.50", "BEVANDE"),
    ("Let it snow", "11.50", "BEVANDE"),
    ("Mela succo", "4.00", "BEVANDE"),
    ("Milkshake", "7.00", "BEVANDE"),
    ("Mirtillo succo", "4.00", "BEVANDE"),
    ("Pera succo", "4.00", "BEVANDE"),
    ("Pesca succo", "4.00", "BEVANDE"),
    ("Red Bull", "6.00", "BEVANDE"),
    ("Sanbitter", "6.00", "BEVANDE"),
    ("Sissi mocktail", "11.50", "BEVANDE"),
    ("Spremuta arancia", "6.00", "BEVANDE"),
    ("Sprite", "4.50", "BEVANDE"),
    ("Succo pomodoro", "4.00", "BEVANDE"),
    ("The limone", "4.00", "BEVANDE"),
    ("The pesca", "4.00", "BEVANDE"),
    ("Amaro del Capo", "6.00", "LIQUORI"),
    ("Amaro Trentino", "6.00", "LIQUORI"),
    ("Anima Nera", "5.00", "LIQUORI"),
    ("Asperula", "5.00", "LIQUORI"),
    ("Averna", "6.00", "LIQUORI"),
    ("Baileys", "6.00", "LIQUORI"),
    ("Barricata", "6.00", "LIQUORI"),
    ("Braulio", "6.00", "LIQUORI"),
    ("Cacao nocciola", "6.00", "LIQUORI"),
    ("Camomilla grappa", "5.00", "LIQUORI"),
    ("Caramello salato", "6.00", "LIQUORI"),
    ("Cirmolo", "5.00", "LIQUORI"),
    ("Cointreau", "5.00", "LIQUORI"),
    ("Fernet Branca", "6.00", "LIQUORI"),
    ("Fernet menta", "6.00", "LIQUORI"),
    ("Fieno grappa", "6.00", "LIQUORI"),
    ("Ginepro", "5.00", "LIQUORI"),
    ("Jack Daniels", "7.00", "LIQUORI"),
    ("Jägermeister", "6.00", "LIQUORI"),
    ("Limoncino", "5.00", "LIQUORI"),
    ("Mela verde", "5.00", "LIQUORI"),
    ("Mirtillo", "5.00", "LIQUORI"),
    ("Montenegro", "6.00", "LIQUORI"),
    ("Moscato", "5.00", "LIQUORI"),
    ("Mugo", "5.00", "LIQUORI"),
    ("Pera Williams", "5.00", "LIQUORI"),
    ("Ramazzotti", "6.00", "LIQUORI"),
    ("Sambuca", "6.00", "LIQUORI"),
    ("Teroldego", "5.00", "LIQUORI"),
    ("Vodka", "5.00", "LIQUORI"),
    ("Gewürztraminer bottiglia", "32.00", "VINO"),
    ("Gewürztraminer calice", "6.00", "VINO"),
    ("Chardonnay MG", "33.00", "VINO"),
    ("Lagrain calice", "6.00", "VINO"),
    ("Lagrein Stella Alpina bottiglia", "38.00", "VINO"),
    ("Lugana calice", "6.00", "VINO"),
    ("Marzemino calice", "6.00", "VINO"),
    ("Marzemino Trentino DOC bottiglia", "35.00", "VINO"),
    ("Morus Brut Millesimato", "52.00", "VINO"),
    ("Morus Brut Rosé", "60.00", "VINO"),
    ("Naonis Jader calice", "5.00", "VINO"),
    ("Nosiola calice", "6.00", "VINO"),
    ("Nosiola Poli Giovanni bottiglia", "34.00", "VINO"),
    ("Pinot bianco calice", "6.00", "VINO"),
    ("Pinot bianco Muri Gries bottiglia", "32.00", "VINO"),
    ("Pinot grigio calice", "6.00", "VINO"),
    ("Pinot grigio MG bottiglia", "32.00", "VINO"),
    ("Pinot nero Cantina Muri Gries calice", "6.50", "VINO"),
    ("Pinot nero MG bottiglia", "40.00", "VINO"),
    ("Prosecco Valdobbiadene calice", "6.00", "VINO"),
    ("Teroldego calice", "6.00", "VINO"),
    ("Teroldego Vigneti delle Dolomiti bottiglia", "35.00", "VINO"),
    ("Trento DOC calice", "8.00", "VINO"),
    ("Vin brulè", "9.00", "VINO"),
    ("1 chilo gelato", "24.00", "GELATI"),
    ("2 gusti take away", "3.50", "GELATI"),
    ("500 gr gelato", "12.00", "GELATI"),
    ("Affogato al caffè", "4.00", "GELATI"),
    ("Affogato Baileys", "10.00", "GELATI"),
    ("Cono/coppetta 1 gusto", "2.00", "GELATI"),
    ("Cono/coppetta 2 gusti", "3.50", "GELATI"),
    ("Cono/coppetta 3 gusti", "4.50", "GELATI"),
    ("Coppa 1", "3.50", "GELATI"),
    ("Coppa 2", "5.00", "GELATI"),
    ("Coppa 3", "6.50", "GELATI"),
    ("Frappè", "8.50", "GELATI"),
    ("Jingle Bell Rock", "11.50", "GELATI"),
    ("Alpino", "12.00", "FOOD"),
    ("Sticks polenta", "25.00", "FOOD"),
    ("Baby tost", "6.00", "FOOD"),
    ("Bocconcino Sissi", "12.00", "FOOD"),
    ("Caprese tortel", "14.00", "FOOD"),
    ("Club sandwich", "8.00", "FOOD"),
    ("Cotoletta", "16.00", "FOOD"),
    ("Crepe cotto formaggio", "8.00", "FOOD"),
    ("Hamburger", "14.00", "FOOD"),
    ("Hamburger vegetariano", "14.00", "FOOD"),
    ("Lardo tortel", "16.00", "FOOD"),
    ("Montanaro", "12.00", "FOOD"),
    ("Omelette cotto formaggio", "13.00", "FOOD"),
    ("Panino speck", "8.50", "FOOD"),
    ("Panino vegetariano", "8.00", "FOOD"),
    ("Patatine fritte", "5.50", "FOOD"),
    ("Piadina cotto", "8.00", "FOOD"),
    ("Piadina light", "8.50", "FOOD"),
    ("Piadina salame", "8.50", "FOOD"),
    ("Piadina speck", "8.80", "FOOD"),
    ("Piadina vegetariana", "8.00", "FOOD"),
    ("Rendena", "8.50", "FOOD"),
    ("Snowboard", "13.00", "FOOD"),
    ("Tirolese", "12.00", "FOOD"),
    ("Tortel uova bacon", "16.00", "FOOD"),
    ("Tortel lardo o speck", "16.00", "FOOD"),
    ("Tortel salsiccia", "18.00", "FOOD"),
    ("Tortel uova", "16.00", "FOOD"),
    ("Toast", "7.00", "FOOD"),
    ("Toast vegetariano", "7.00", "FOOD"),
    ("Uova bacon", "13.00", "FOOD"),
    ("Crepes alla Nutella/marmellata", "5.50", "DOLCI"),
    ("Crepes miele noci", "5.50", "DOLCI"),
    ("Crepes Nutella/marmellata + gelato", "7.00", "DOLCI"),
    ("Crepes topping caramello/nocciola/frutti", "6.50", "DOLCI"),
    ("Crostata marmellata", "5.00", "DOLCI"),
    ("Crostata Nutella", "5.00", "DOLCI"),
    ("Crostata vegana", "5.00", "DOLCI"),
    ("Fagottino mela", "3.50", "DOLCI"),
    ("Fetta crostata asporto", "4.00", "DOLCI"),
    ("Fetta Sacher asporto", "5.50", "DOLCI"),
    ("Fetta strudel asporto", "5.50", "DOLCI"),
    ("Gluten free snack", "3.00", "DOLCI"),
    ("Krapfen crema", "2.50", "DOLCI"),
    ("Krapfen marmellata", "2.50", "DOLCI"),
    ("Krapfen Nutella", "2.50", "DOLCI"),
    ("Krapfen pistacchio", "2.50", "DOLCI"),
    ("Krapfen vuoto", "2.50", "DOLCI"),
    ("Lintz", "6.50", "DOLCI"),
    ("Macarons", "2.00", "DOLCI"),
    ("Marshmallow piccolo", "0.50", "DOLCI"),
    ("Meringa", "1.50", "DOLCI"),
    ("Mignon pasticcini", "1.50", "DOLCI"),
    ("Mini Sacherina", "2.50", "DOLCI"),
    ("Muffin", "3.80", "DOLCI"),
    ("Occhio di bue cioccolato", "3.70", "DOLCI"),
    ("Occhio di bue marmellata", "3.70", "DOLCI"),
    ("Sacher", "6.50", "DOLCI"),
    ("Senza glutine senza lattosio", "12.00", "DOLCI"),
    ("Sissi souvenir", "5.90", "DOLCI"),
    ("Strudel di mele", "6.50", "DOLCI"),
    ("Strudel piccolo", "18.50", "DOLCI"),
    ("Strudel + vaniglia gelato", "7.50", "DOLCI"),
    ("Torta di carote", "6.00", "DOLCI"),
    ("French toast", "13.00", "DOLCI"),
    ("Mele torta", "6.50", "DOLCI"),
    ("Aperitivo Assenzio Lurisia", "6.00", "APERITIVI"),
    ("Aurora Boreale", "14.00", "APERITIVI"),
    ("Baby It's Cold", "14.00", "APERITIVI"),
    ("Bloody Virgin", "6.00", "APERITIVI"),
    ("Campari shakerato", "7.00", "APERITIVI"),
    ("Campari soda", "6.00", "APERITIVI"),
    ("Cinnamon Snow Mule", "14.00", "APERITIVI"),
    ("Coconut Snowdrift", "14.00", "APERITIVI"),
    ("Frosted Maracuja", "14.00", "APERITIVI"),
    ("Gingerbread Martini", "14.00", "APERITIVI"),
    ("Limoncello Spritz", "10.00", "APERITIVI"),
    ("Marshmallow Martini", "14.00", "APERITIVI"),
    ("Merry Kiss Shot", "14.00", "APERITIVI"),
    ("Mr Sandman", "14.00", "APERITIVI"),
    ("Snowflake", "14.00", "APERITIVI"),
    ("Spritz misto", "8.00", "APERITIVI"),
    ("Americano", "10.00", "APERITIVI"),
    ("Lavender Spritz", "12.00", "APERITIVI"),
    ("Analcolico frutta", "8.00", "APERITIVI"),
    ("Aperitivo Lurisia genziana", "6.00", "APERITIVI"),
    ("Aperol Spritz", "8.00", "APERITIVI"),
    ("Bloody Mary", "12.00", "APERITIVI"),
    ("Calice Gewürztraminer", "6.00", "APERITIVI"),
    ("Calice Lagrain", "6.00", "APERITIVI"),
    ("Calice Pinot Grigio", "6.00", "APERITIVI"),
    ("Calice Prosecco", "6.00", "APERITIVI"),
    ("Calice Teroldego", "6.00", "APERITIVI"),
    ("Calice Trento DOC", "8.00", "APERITIVI"),
    ("Campari Spritz", "8.00", "APERITIVI"),
    ("Cocktail 12€ base", "12.00", "APERITIVI"),
    ("Forst", "5.00", "APERITIVI"),
    ("Gin tonic 12€ base", "12.00", "APERITIVI"),
    ("Hugo", "8.00", "APERITIVI"),
    ("Martini", "6.00", "APERITIVI"),
    ("Media Grimbergen", "8.00", "APERITIVI"),
    ("Media Kronenbourg", "7.00", "APERITIVI"),
    ("Moscow Mule", "12.00", "APERITIVI"),
    ("Negroni", "10.00", "APERITIVI"),
    ("Negrosky", "10.00", "APERITIVI"),
    ("Peroni doppio malto", "7.50", "APERITIVI"),
    ("Franz Joseph Spritz", "14.00", "APERITIVI"),
    ("Spritz estivo", "12.00", "APERITIVI"),
    ("Piccola Kronenbourg", "4.00", "APERITIVI"),
    ("Premium cocktail", "14.00", "APERITIVI"),
    ("Radler media", "7.00", "APERITIVI"),
    ("Radler piccola", "4.00", "APERITIVI"),
    ("Sanbitter", "6.00", "APERITIVI"),
    ("Sissi aperitivo", "10.00", "APERITIVI"),
]


CLIENT_VISIBLE_ITEMS = {
    ("CAFFETTERIA", "Americano caffè"),
    ("CAFFETTERIA", "Bombardino"),
    ("CAFFETTERIA", "Caffè"),
    ("CAFFETTERIA", "Caffè con panna"),
    ("CAFFETTERIA", "Cappuccino"),
    ("CAFFETTERIA", "Cappuccino miele cannella"),
    ("CAFFETTERIA", "Cioccolata con panna"),
    ("CAFFETTERIA", "Corretto"),
    ("CAFFETTERIA", "Decaffeinato"),
    ("CAFFETTERIA", "Flat white"),
    ("CAFFETTERIA", "Ginseng grande"),
    ("CAFFETTERIA", "Ginseng piccolo"),
    ("CAFFETTERIA", "Latte caldo"),
    ("CAFFETTERIA", "Latte macchiato"),
    ("CAFFETTERIA", "Orzo grande"),
    ("CAFFETTERIA", "Orzo piccolo"),
    ("CAFFETTERIA", "Punch mandarino"),
    ("CAFFETTERIA", "Tè / tisana"),
    ("CAFFETTERIA", "Vin brulè"),
    ("BEVANDE", "ACE succo"),
    ("BEVANDE", "Acqua 0,5 frizzante Pejo"),
    ("BEVANDE", "Acqua 0,5 naturale Pejo"),
    ("BEVANDE", "Albicocca succo"),
    ("BEVANDE", "Ananas succo"),
    ("BEVANDE", "Aranciata"),
    ("BEVANDE", "Cedrata"),
    ("BEVANDE", "Chinotto"),
    ("BEVANDE", "Coca Cola"),
    ("BEVANDE", "Crodino"),
    ("BEVANDE", "Lemonsoda"),
    ("BEVANDE", "Limonata"),
    ("BEVANDE", "Mela succo"),
    ("BEVANDE", "Mirtillo succo"),
    ("BEVANDE", "Pera succo"),
    ("BEVANDE", "Pesca succo"),
    ("BEVANDE", "Sanbitter"),
    ("BEVANDE", "Spremuta arancia"),
    ("BEVANDE", "Sprite"),
    ("BEVANDE", "Succo pomodoro"),
    ("BEVANDE", "The limone"),
    ("BEVANDE", "The pesca"),
    ("LIQUORI", "Barricata"),
    ("VINO", "Gewürztraminer bottiglia"),
    ("VINO", "Gewürztraminer calice"),
    ("VINO", "Lagrain calice"),
    ("VINO", "Lagrein Stella Alpina bottiglia"),
    ("VINO", "Lugana calice"),
    ("VINO", "Marzemino calice"),
    ("VINO", "Marzemino Trentino DOC bottiglia"),
    ("VINO", "Morus Brut Millesimato"),
    ("VINO", "Pinot grigio calice"),
    ("VINO", "Pinot grigio MG bottiglia"),
    ("VINO", "Prosecco Valdobbiadene calice"),
    ("VINO", "Teroldego calice"),
    ("VINO", "Teroldego Vigneti delle Dolomiti bottiglia"),
    ("VINO", "Trento DOC calice"),
    ("FOOD", "Alpino"),
    ("FOOD", "Baby tost"),
    ("FOOD", "Bocconcino Sissi"),
    ("FOOD", "Caprese tortel"),
    ("FOOD", "Club sandwich"),
    ("FOOD", "Cotoletta"),
    ("FOOD", "Crepe cotto formaggio"),
    ("FOOD", "Hamburger"),
    ("FOOD", "Hamburger vegetariano"),
    ("FOOD", "Lardo tortel"),
    ("FOOD", "Montanaro"),
    ("FOOD", "Omelette cotto formaggio"),
    ("FOOD", "Panino vegetariano"),
    ("FOOD", "Patatine fritte"),
    ("FOOD", "Piadina cotto"),
    ("FOOD", "Piadina speck"),
    ("FOOD", "Rendena"),
    ("FOOD", "Snowboard"),
    ("FOOD", "Sticks polenta"),
    ("FOOD", "Tirolese"),
    ("FOOD", "Toast"),
    ("FOOD", "Toast vegetariano"),
    ("FOOD", "Tortel lardo o speck"),
    ("FOOD", "Tortel salsiccia"),
    ("FOOD", "Tortel uova bacon"),
    ("FOOD", "Uova bacon"),
    ("DOLCI", "Crepes alla Nutella/marmellata"),
    ("DOLCI", "Crepes miele noci"),
    ("DOLCI", "Crepes Nutella/marmellata + gelato"),
    ("DOLCI", "Crepes topping caramello/nocciola/frutti"),
    ("DOLCI", "Crostata marmellata"),
    ("DOLCI", "Crostata Nutella"),
    ("DOLCI", "Crostata vegana"),
    ("DOLCI", "French toast"),
    ("DOLCI", "Sacher"),
    ("DOLCI", "Strudel + vaniglia gelato"),
    ("DOLCI", "Strudel di mele"),
    ("DOLCI", "Torta di carote"),
    ("APERITIVI", "Americano"),
    ("APERITIVI", "Analcolico frutta"),
    ("APERITIVI", "Aperitivo Assenzio Lurisia"),
    ("APERITIVI", "Aperitivo Lurisia genziana"),
    ("APERITIVI", "Aperol Spritz"),
    ("APERITIVI", "Bloody Mary"),
    ("APERITIVI", "Calice Gewürztraminer"),
    ("APERITIVI", "Calice Lagrain"),
    ("APERITIVI", "Calice Pinot Grigio"),
    ("APERITIVI", "Calice Prosecco"),
    ("APERITIVI", "Calice Teroldego"),
    ("APERITIVI", "Calice Trento DOC"),
    ("APERITIVI", "Campari shakerato"),
    ("APERITIVI", "Campari soda"),
    ("APERITIVI", "Cocktail 12€ base"),
    ("APERITIVI", "Forst"),
    ("APERITIVI", "Gin tonic 12€ base"),
    ("APERITIVI", "Limoncello Spritz"),
    ("APERITIVI", "Media Kronenbourg"),
    ("APERITIVI", "Moscow Mule"),
    ("APERITIVI", "Negroni"),
    ("APERITIVI", "Negrosky"),
    ("APERITIVI", "Peroni doppio malto"),
    ("APERITIVI", "Piccola Kronenbourg"),
    ("APERITIVI", "Premium cocktail"),
    ("APERITIVI", "Sanbitter"),
    ("APERITIVI", "Sissi aperitivo"),
}


CATEGORY_NAMES = {
    "APERITIVI": "Aperitivi",
    "BEVANDE": "Bibite",
    "CAFFETTERIA": "Caffetteria",
    "DOLCI": "Dolci",
    "FOOD": "Food",
    "GELATI": "Gelati",
    "LIQUORI": "Grappe e liquori",
    "VINO": "Vino al calice e bottiglie",
}

BAR_CATEGORIES = {"APERITIVI", "BEVANDE", "CAFFETTERIA", "LIQUORI", "VINO"}


def menu_item_key(name, raw_category):
    return (raw_category.strip().upper(), name)


CATEGORY_OVERRIDES = {
    ("APERITIVI", "Analcolico frutta"): "Analcolici",
    ("APERITIVI", "Aperitivo Assenzio Lurisia"): "Analcolici",
    ("APERITIVI", "Aperitivo Lurisia genziana"): "Analcolici",
    ("APERITIVI", "Bloody Mary"): "Cocktails",
    ("APERITIVI", "Bloody Virgin"): "Analcolici",
    ("APERITIVI", "Cocktail 12€ base"): "Cocktails",
    ("APERITIVI", "Gin tonic 12€ base"): "Cocktails",
    ("APERITIVI", "Moscow Mule"): "Cocktails",
    ("APERITIVI", "Forst"): "Birra",
    ("APERITIVI", "Media Grimbergen"): "Birra",
    ("APERITIVI", "Media Kronenbourg"): "Birra",
    ("APERITIVI", "Peroni doppio malto"): "Birra",
    ("APERITIVI", "Piccola Kronenbourg"): "Birra",
    ("APERITIVI", "Radler media"): "Birra",
    ("APERITIVI", "Radler piccola"): "Birra",
    ("APERITIVI", "Calice Gewürztraminer"): "Vino al calice e bottiglie",
    ("APERITIVI", "Calice Lagrain"): "Vino al calice e bottiglie",
    ("APERITIVI", "Calice Pinot Grigio"): "Vino al calice e bottiglie",
    ("APERITIVI", "Calice Prosecco"): "Vino al calice e bottiglie",
    ("APERITIVI", "Calice Teroldego"): "Vino al calice e bottiglie",
    ("APERITIVI", "Calice Trento DOC"): "Vino al calice e bottiglie",
    ("APERITIVI", "Aurora Boreale"): "Premium Cocktails",
    ("APERITIVI", "Baby It's Cold"): "Premium Cocktails",
    ("APERITIVI", "Cinnamon Snow Mule"): "Premium Cocktails",
    ("APERITIVI", "Coconut Snowdrift"): "Premium Cocktails",
    ("APERITIVI", "Franz Joseph Spritz"): "Premium Cocktails",
    ("APERITIVI", "Frosted Maracuja"): "Premium Cocktails",
    ("APERITIVI", "Gingerbread Martini"): "Premium Cocktails",
    ("APERITIVI", "Lavender Spritz"): "Premium Cocktails",
    ("APERITIVI", "Marshmallow Martini"): "Premium Cocktails",
    ("APERITIVI", "Merry Kiss Shot"): "Premium Cocktails",
    ("APERITIVI", "Mr Sandman"): "Premium Cocktails",
    ("APERITIVI", "Premium cocktail"): "Premium Cocktails",
    ("APERITIVI", "Snowflake"): "Premium Cocktails",
    ("APERITIVI", "Sanbitter"): "Analcolici",
    ("APERITIVI", "Sissi aperitivo"): "Analcolici",
    ("BEVANDE", "Crodino"): "Analcolici",
    ("BEVANDE", "Sanbitter"): "Analcolici",
    ("BEVANDE", "Sissi mocktail"): "Analcolici",
    ("BEVANDE", "Succo pomodoro"): "Analcolici",
    ("DOLCI", "Fagottino mela"): "Colazione",
    ("DOLCI", "French toast"): "Colazione",
    ("DOLCI", "Krapfen crema"): "Colazione",
    ("DOLCI", "Krapfen marmellata"): "Colazione",
    ("DOLCI", "Krapfen Nutella"): "Colazione",
    ("DOLCI", "Krapfen pistacchio"): "Colazione",
    ("DOLCI", "Krapfen vuoto"): "Colazione",
    ("FOOD", "Alpino"): "Panini",
    ("FOOD", "Baby tost"): "Colazione",
    ("FOOD", "Bocconcino Sissi"): "Panini",
    ("FOOD", "Hamburger"): "Panini",
    ("FOOD", "Hamburger vegetariano"): "Panini",
    ("FOOD", "Montanaro"): "Panini",
    ("FOOD", "Panino speck"): "Panini",
    ("FOOD", "Panino vegetariano"): "Panini",
    ("FOOD", "Patatine fritte"): "Da stuzzicare",
    ("FOOD", "Rendena"): "Panini",
    ("FOOD", "Snowboard"): "Panini",
    ("FOOD", "Sticks polenta"): "Da stuzzicare",
    ("FOOD", "Tirolese"): "Panini",
    ("FOOD", "Uova bacon"): "Colazione",
}


def is_client_visible(name, raw_category):
    return menu_item_key(name, raw_category) in CLIENT_VISIBLE_ITEMS


def normalized_category(raw_category, name=None):
    key = raw_category.strip().upper()
    if name:
        override = CATEGORY_OVERRIDES.get((key, name))
        if override:
            return override
        if key == "FOOD":
            return "Spuntino Salato"
    return CATEGORY_NAMES.get(key, raw_category.title())


def station_for_category(raw_category):
    key = raw_category.strip().upper()
    return "bar" if key in BAR_CATEGORIES else "kitchen"


def catalog_items():
    for name, price, raw_category, *_rest in RAW_MENU:
        tags = [CLIENT_MENU_TAG] if is_client_visible(name, raw_category) else []
        yield {
            "name": name,
            "description": "",
            "price": Decimal(price),
            "category": normalized_category(raw_category, name),
            "image_url": "",
            "station": station_for_category(raw_category),
            "tags": tags,
            "composition": "",
            "allergens": [],
            "is_available": True,
            "is_promoted": False,
            "preparation_minutes": 5,
            "portion_weight": "",
            "calories": None,
        }
