from decimal import Decimal

from apps.core.menu_content import ALLERGEN_REVIEW_TAG, menu_content

CLIENT_MENU_TAG = "client"
MANUAL_CHECK_TAG = "manual_check"
SEASONAL_TAG = "seasonal"
STATION_CHECK_TAG = "station_check"

GELATO_GUSTI = ("Nocciola", "Yogurt", "Fragola", "Vaniglia", "Cacao")
GELATO_MODIFIER_ITEMS = {
    "Cono/Coppetta 1 gusto",
    "Cono/Coppetta 2 gusti",
    "Cono/Coppetta 3 gusti",
    "Coppa 1",
    "Coppa 2",
    "Coppa 3",
    "2 gusti take away",
}


# (key, display name, color)
MENU_CATEGORIES = [
    ("caffetteria", "Caffetteria", "#E0823A"),
    ("bevande", "Bevande", "#5BAEDC"),
    ("analcolici", "Analcolici", "#3E9C63"),
    ("birra", "Birra", "#DFAF2B"),
    ("vino", "Vino", "#C0463B"),
    ("cocktail-aperitivi", "Cocktail & Aperitivi", "#7CC488"),
    ("liquori-grappe-amari", "Liquori/Grappe/Amari", "#8A6FC0"),
    ("pasticceria", "Pasticceria", "#B88746"),
    ("dolci", "Dolci", "#C95F8A"),
    ("gelati", "Gelati", "#3C7BCF"),
    ("panini", "Panini", "#DFAF2B"),
    ("piadine", "Piadine", "#C9A227"),
    ("tortel", "Tortel", "#B97832"),
    ("secondi", "Secondi", "#A94D3E"),
    ("uova-colazione-salata", "Uova/colazione salata", "#6F8F42"),
    ("toast", "Toast", "#9A7A45"),
    ("fritti-stuzzichini", "Fritti/stuzzichini", "#B66A2D"),
]


# (station, category, category_key, [(name, price, *tags)])
MENU_SECTIONS = [
    (
        "bar",
        "Caffetteria",
        "caffetteria",
        [
            ("Caffè (espresso)", "1.50"),
            ("Doppio caffè", "3.00"),
            ("Lungo caffè", "1.50"),
            ("Ristretto", "1.50"),
            ("Macchiato", "1.50"),
            ("Macchiato freddo", "1.50"),
            ("Macchiatone", "2.00"),
            ("Marocchino", "2.50"),
            ("Corretto", "3.00"),
            ("Decaffeinato", "2.00"),
            ("Deca macchiato", "2.00"),
            ("Deca macchiato freddo", "2.00"),
            ("Americano caffè", "2.00"),
            ("Cappuccino", "3.00"),
            ("Cappuccino deca", "3.50"),
            ("Cappuccino miele e cannella", "4.00"),
            ("Cappuccino panna", "5.00"),
            ("Cappuccino soya", "3.50"),
            ("Cappuccino no lattosio", "3.00"),
            ("Schiumato (macchiato)", "1.50"),
            ("Schiumetta", "1.50"),
            ("Latte caldo", "2.00"),
            ("Latte macchiato", "3.50"),
            ("Flat white", "5.00"),
            ("Caffè con panna", "2.50"),
            ("Caffè shakerato", "5.00"),
            ("Orzo grande", "3.00"),
            ("Orzo piccolo", "2.50"),
            ("Orzo macchiato", "2.50"),
            ("Cappuccino orzo", "3.50"),
            ("Ginseng grande", "3.00"),
            ("Ginseng piccolo", "2.50"),
            ("Tè / Tisana", "3.50"),
            ("Camomilla", "3.00"),
            ("Cioccolata calda", "5.50"),
            ("Cioccolata calda bianca", "5.50"),
            ("Cioccolata con panna", "6.00"),
            ("Cioccolata baby", "3.00"),
            ("Cioccolata bianca menta", "6.50"),
            ("Cioccolata arancia cannella", "7.00"),
            ("Cioccolata cocco/mou", "7.00"),
            ("Cioccolata peperoncino", "7.00"),
            ("Bombardino", "5.00"),
            ("Punch mandarino", "5.00"),
        ],
    ),
    (
        "bar",
        "Bevande",
        "bevande",
        [
            ("Acqua 0,5 naturale Pejo", "2.50"),
            ("Acqua 0,5 frizzante Pejo", "2.50"),
            ("Acqua 0,5 asporto", "2.00"),
            ("Acqua 1 L Pejo", "4.00"),
            ("Acqua 1 L asporto", "3.50"),
            ("Acqua menta/lampone", "3.00"),
            ("Bicchiere H2O", "0.50"),
            ("Bicchiere H2O frizzante", "0.50"),
            ("Coca Cola", "4.50"),
            ("Coca Zero", "4.50"),
            ("Sprite", "4.50"),
            ("Lemonsoda", "4.50"),
            ("Limonata", "4.50"),
            ("Aranciata", "4.50"),
            ("Cedrata", "4.50"),
            ("Chinotto", "4.50"),
            ("Acqua tonica", "4.50"),
            ("Red Bull", "6.00", MANUAL_CHECK_TAG),
            ("Red Bull Arancia", "6.00", MANUAL_CHECK_TAG),
            ("Monster", "6.00", MANUAL_CHECK_TAG),
            ("Succo ACE", "4.00"),
            ("Succo albicocca", "4.00"),
            ("Succo ananas", "4.00"),
            ("Succo mela verde", "4.00"),
            ("Succo mirtillo", "4.00"),
            ("Succo pera", "4.00"),
            ("Succo pompelmo", "4.00"),
            ("Succo pesca", "4.00"),
            ("Succo pomodoro", "4.00"),
            ("Spremuta d'arancia", "6.00"),
            ("Tè freddo limone", "4.00"),
            ("Tè freddo pesca", "4.00"),
            ("Milkshake", "7.00"),
        ],
    ),
    (
        "bar",
        "Analcolici",
        "analcolici",
        [
            ("Crodino", "4.00"),
            ("San Bitter", "6.00"),
            ("Aperitivo Assenzio Lurisia", "6.00"),
            ("Aperitivo Genziana Lurisia", "6.00"),
            ("Analcolico frutta", "8.00"),
            ("Analcolico Sissi", "8.00"),
            ("Bloody Virgin", "6.00"),
            ("Virgin Hugo", "6.00"),
            ("Virgin Mojito", "8.00"),
            ("Sissi Mocktail", "11.50"),
            ("Let It Snow", "11.50", SEASONAL_TAG),
            ("Winter Wonderland", "11.50", SEASONAL_TAG),
        ],
    ),
    (
        "bar",
        "Birra",
        "birra",
        [
            ("Forst media", "5.00"),
            ("Kronenbourg 1664 media (0,5)", "7.00"),
            ("Kronenbourg 1664 piccola (0,25)", "4.00"),
            ("Grimbergen media", "8.00"),
            ("Peroni Doppio Malto", "7.50"),
            ("Radler media", "7.00"),
            ("Radler piccola", "4.00"),
        ],
    ),
    (
        "bar",
        "Vino",
        "vino",
        [
            ("Pinot Grigio calice", "6.00"),
            ("Pinot Grigio bottiglia", "33.00"),
            ("Gewürztraminer calice", "6.00"),
            ("Gewürztraminer bottiglia", "35.00"),
            ("Lugana calice", "6.00"),
            ("Chardonnay MG bottiglia", "33.00"),
            ("Nosiola calice", "6.00"),
            ("Nosiola bottiglia", "34.00"),
            ("Pinot Bianco Muri Gries calice", "6.00"),
            ("Pinot Bianco Muri Gries bottiglia", "32.00"),
            ("Naonis Jader calice", "5.00"),
            ("Lagrein calice", "6.00"),
            ("Lagrein bottiglia", "38.00"),
            ("Marzemino calice", "6.00"),
            ("Marzemino bottiglia", "35.00"),
            ("Teroldego calice", "6.00"),
            ("Teroldego bottiglia", "35.00"),
            ("Pinot Nero calice", "6.50"),
            ("Pinot Nero bottiglia", "40.00"),
            ("Prosecco Valdobbiadene calice", "6.00"),
            ("Prosecco Valdobbiadene bottiglia", "55.00"),
            ("Trento DOC calice", "8.00"),
            ("Trento DOC bottiglia", "52.00"),
            ("Trento DOC Rosé Millesimato calice", "9.00"),
            ("Morus Brut Millesimato bottiglia", "52.00"),
            ("Morus Brut Rosé bottiglia", "60.00"),
            ("Bottiglia premium (nome da confermare)", "96.00", MANUAL_CHECK_TAG),
        ],
    ),
    (
        "bar",
        "Cocktail & Aperitivi",
        "cocktail-aperitivi",
        [
            ("Aperol Spritz", "8.00"),
            ("Campari Spritz", "8.00", MANUAL_CHECK_TAG),
            ("Limoncello Spritz", "10.00"),
            ("Spritz misto", "8.00"),
            ("Spritz estivo", "12.00", SEASONAL_TAG, MANUAL_CHECK_TAG),
            ("Lavender Spritz", "12.00"),
            ("Franz Joseph Spritz", "14.00"),
            ("Hugo", "8.00"),
            ("Sissi Hugo", "10.00"),
            ("Martini", "6.00"),
            ("Negroni", "10.00"),
            ("Negrosky (Negroni Sbagliato)", "10.00"),
            ("Americano", "10.00"),
            ("Campari Soda", "6.00"),
            ("Campari Shakerato", "7.00"),
            ("Moscow Mule", "12.00"),
            ("Gin Tonic (base Bombay)", "12.00"),
            ("Cocktail 12€ base", "12.00"),
            ("Premium Cocktail", "14.00"),
            ("Bloody Mary", "12.00"),
            ("Margarita", "12.00"),
            ("Caipiroska / Caipirinha", "12.00"),
            ("Cosmopolitan", "12.00"),
            ("Cuba Libre", "12.00"),
            ("Sex on the Beach", "12.00"),
            ("Long Island Iced Tea", "12.00"),
            ("Tequila Sunrise", "12.00"),
            ("Vodka Tonic", "12.00"),
            ("Daiquiri", "10.00"),
            ("Mimosa", "10.00"),
            ("Sissi Signature Cocktail", "12.00"),
            ("Aurora Boreale", "14.00", SEASONAL_TAG),
            ("Baby It's Cold", "14.00", SEASONAL_TAG),
            ("Cinnamon Snow Mule", "14.00", SEASONAL_TAG),
            ("Coconut Snowdrift", "14.00", SEASONAL_TAG),
            ("Frosted Maracuja", "14.00", SEASONAL_TAG),
            ("Gingerbread Martini", "14.00", SEASONAL_TAG),
            ("Marshmallow Martini", "14.00", SEASONAL_TAG),
            ("Merry Kiss Shot", "14.00", SEASONAL_TAG),
            ("Mr Sandman", "14.00", SEASONAL_TAG),
            ("Snowflake", "14.00", SEASONAL_TAG),
        ],
    ),
    (
        "bar",
        "Liquori/Grappe/Amari",
        "liquori-grappe-amari",
        [
            ("Amaro del Capo", "6.00"),
            ("Amaro Trentino", "6.00"),
            ("Anima Nera", "5.00"),
            ("Asperula", "5.00"),
            ("Averna", "6.00"),
            ("Baileys", "6.00"),
            ("Grappa Barricata", "6.00"),
            ("Braulio", "6.00"),
            ("Grappa Cacao e Nocciola", "6.00"),
            ("Grappa Camomilla", "5.00"),
            ("Grappa Caramello Salato", "6.00"),
            ("Grappa Cirmolo", "5.00"),
            ("Cointreau", "5.00"),
            ("Fernet Branca", "6.00"),
            ("Fernet Menta", "6.00"),
            ("Grappa Fieno", "6.00"),
            ("Grappa Ginepro", "5.00"),
            ("Jack Daniel's", "7.00"),
            ("Jägermeister", "6.00"),
            ("Limoncino", "5.00"),
            ("Grappa Mela Verde", "5.00"),
            ("Grappa Mirtillo", "5.00"),
            ("Montenegro", "6.00"),
            ("Moscato", "5.00"),
            ("Grappa Mugo", "5.00"),
            ("Grappa Pera Williams", "5.00"),
            ("Ramazzotti", "6.00"),
            ("Sambuca", "6.00"),
            ("Grappa Teroldego", "5.00"),
            ("Vodka", "5.00"),
        ],
    ),
    (
        "bar",
        "Pasticceria",
        "pasticceria",
        [
            ("Croissant crema", "2.50"),
            ("Croissant marmellata", "2.50"),
            ("Croissant nutella", "2.50"),
            ("Croissant pistacchio", "2.50"),
            ("Croissant vuoto", "2.50"),
            ("Croissant vegano", "3.00"),
            ("Krapfen crema", "2.50"),
            ("Krapfen marmellata", "2.50"),
            ("Krapfen nutella", "2.50"),
            ("Biscotto Occhio di Bue cioccolato", "3.70"),
            ("Biscotto Occhio di Bue marmellata", "3.70"),
            ("Biscottino", "2.50"),
            ("Macarons", "2.50"),
            ("Biscotti senza lattosio", "2.50"),
            ("Biscotti", "2.50"),
            ("Crêpe con nutella o miele", "3.70"),
        ],
    ),
    (
        "bar",
        "Dolci",
        "dolci",
        [
            ("Sacher con panna", "6.50"),
            ("Strudel di mele", "6.50", MANUAL_CHECK_TAG),
            ("Crostata del giorno", "5.00"),
            ("Crostata vegana", "5.50"),
            ("Torta di carote con panna", "6.50"),
            ("Torta di carote con gelato", "7.00"),
            ("Cheesecake Sissi", "7.00", MANUAL_CHECK_TAG),
            ("Crêpes con Nutella", "6.00", MANUAL_CHECK_TAG),
            ("French Toast con nutella e noci", "7.00", STATION_CHECK_TAG),
        ],
    ),
    (
        "bar",
        "Gelati",
        "gelati",
        [
            ("Cono/Coppetta 1 gusto", "2.00"),
            ("Cono/Coppetta 2 gusti", "3.50"),
            ("Cono/Coppetta 3 gusti", "4.50"),
            ("Coppa 1", "3.50"),
            ("Coppa 2", "5.00"),
            ("Coppa 3", "6.50"),
            ("Affogato al caffè", "4.00"),
            ("Affogato Baileys", "10.00", MANUAL_CHECK_TAG),
            ("Frappé", "8.50"),
            ("Gelato 500 gr asporto", "12.00"),
            ("Gelato 1 kg asporto", "24.00"),
            ("2 gusti take away", "3.50"),
            ("Jingle Bell Rock", "11.50", SEASONAL_TAG),
        ],
    ),
    (
        "kitchen",
        "Panini",
        "panini",
        [
            ("Alpino", "12.00"),
            ("Caprese", "12.00"),
            ("Insalata", "12.00"),
            ("Bocconcino Sissi", "12.00"),
            ("Sissi Club Sandwich", "8.00", STATION_CHECK_TAG),
            ("Hamburger", "14.00"),
            ("Hamburger vegetariano", "14.00"),
            ("Panino vegetariano", "8.00"),
            ("Montanaro", "12.00"),
            ("Snowboard", "13.00"),
            ("Tirolese", "12.00"),
            ("Rendena", "8.50"),
            ("Hot Dog Alpino", "12.00"),
        ],
    ),
    (
        "kitchen",
        "Piadine",
        "piadine",
        [
            ("Piadina cotto", "8.00"),
            ("Piadina light", "8.50"),
            ("Piadina speck", "8.80"),
            ("Piadina vegetariana", "8.00"),
        ],
    ),
    (
        "kitchen",
        "Tortel",
        "tortel",
        [
            ("Tortel caprese", "14.00"),
            ("Tortel lardo", "16.00"),
            ("Tortel uova e bacon", "16.00"),
            ("Tortel lardo o speck", "16.00"),
            ("Tortel salsiccia", "18.00"),
            ("Tortel uova", "16.00"),
            ("Tortel alla piastra e crauti", "18.00", MANUAL_CHECK_TAG),
        ],
    ),
    (
        "kitchen",
        "Secondi",
        "secondi",
        [
            ("Cotoletta (con patatine)", "16.00"),
            ("Spiedino di pollo", "14.00"),
            ("Nuggets", "6.00"),
            ("Omelette cotto e formaggio", "13.00"),
        ],
    ),
    (
        "kitchen",
        "Uova/colazione salata",
        "uova-colazione-salata",
        [
            ("Uova e bacon", "13.00"),
            ("Crêpe cotto e fontina", "8.00"),
        ],
    ),
    (
        "kitchen",
        "Toast",
        "toast",
        [
            ("Toast", "7.00", STATION_CHECK_TAG),
            ("Toast vegetariano", "7.00", STATION_CHECK_TAG),
            ("Baby Toast", "6.00", STATION_CHECK_TAG),
        ],
    ),
    (
        "kitchen",
        "Fritti/stuzzichini",
        "fritti-stuzzichini",
        [
            ("Patatine fritte", "5.50"),
            ("Sticks di polenta / tagliere", "25.00"),
        ],
    ),
]


def menu_categories():
    for sort_order, (key, name, color) in enumerate(MENU_CATEGORIES):
        yield {
            "key": key,
            "name": name,
            "color": color,
            "sort_order": sort_order,
        }


def catalog_items():
    seen = set()
    gusti = ", ".join(GELATO_GUSTI)
    for station, category, category_key, rows in MENU_SECTIONS:
        for name, price, *extra_tags in rows:
            key = (station, category, name)
            if key in seen:
                raise ValueError(f"Duplicate Sissi menu item: {key}")
            seen.add(key)

            tags = [CLIENT_MENU_TAG, *extra_tags]
            content = menu_content(name, category)
            description = content["description"]
            composition = content["composition"]
            if name in GELATO_MODIFIER_ITEMS:
                tags.append("modifier:gelato_gusti")
                description = f"Gusti: {gusti}"
                composition = description
            tags.append(ALLERGEN_REVIEW_TAG)

            yield {
                "name": name,
                "description": description,
                "price": Decimal(price).quantize(Decimal("0.01")),
                "category": category,
                "category_key": category_key,
                "image_url": "",
                "station": station,
                "tags": tags,
                "composition": composition,
                "allergens": content["allergens"],
                "is_available": True,
                "is_promoted": False,
                "preparation_minutes": 12 if station == "kitchen" else 5,
                "portion_weight": "",
                "calories": None,
            }
